/// Renders a ``PanewrightConfig`` back into `panewright.toml` syntax — the
/// inverse of ``ConfigParser``. Used by the i3 importer (and eventually the
/// visual editor's save path).
public enum PanewrightConfigSerializer {
    public static func emit(_ config: PanewrightConfig) -> String {
        var lines: [String] = []
        lines.append("# Generated by Panewright.")
        lines.append("modifier = \"\(config.modifier.rawValue)\"")
        if config.modifier == .leader {
            lines.append("leader-key = \"\(config.leaderKey)\"")
        }
        lines.append("focus-follows-mouse = \(config.focusFollowsMouse)")
        if config.workspaceChangedHook != nil || config.focusChangedHook != nil {
            lines.append("")
            lines.append("[hooks]")
            if let hook = config.workspaceChangedHook {
                lines.append("workspace-changed = \"\(hook)\"")
            }
            if let hook = config.focusChangedHook {
                lines.append("focus-changed = \"\(hook)\"")
            }
        }
        if !config.floatingApps.isEmpty {
            lines.append("floating-apps = [")
            for app in config.floatingApps {
                lines.append("  \"\(app)\",")
            }
            lines.append("]")
        }
        lines.append("")
        lines.append("[gaps]")
        lines.append("inner = \(config.gaps.inner)")
        lines.append("outer = \(config.gaps.outer)")
        lines.append("")
        lines.append("[border]")
        lines.append("enabled = \(config.focusBorder.enabled)")
        lines.append("width = \(config.focusBorder.width)")
        lines.append("active-color = \"\(config.focusBorder.activeColor)\"")
        lines.append("inactive-color = \"\(config.focusBorder.inactiveColor)\"")
        lines.append("")
        lines.append("[bar]")
        lines.append("enabled = \(config.statusBar.enabled)")
        lines.append("theme = \"\(config.statusBar.theme.rawValue)\"")
        if let accent = config.statusBar.accentColor {
            lines.append("accent-color = \"\(accent)\"")
        }
        lines.append("")
        lines.append("[todo]")
        lines.append("enabled = \(config.todo.enabled)")
        lines.append("")
        lines.append("[pills]")
        lines.append("enabled = \(config.pills.enabled)")
        lines.append("drag-to-bar = \(config.pills.dragToBar)")
        // Tokens live in the Keychain, never here.
        let services: [(String, IntegrationsConfig.Service)] = [
            ("github", config.integrations.github),
            ("gitlab", config.integrations.gitlab),
            ("bitbucket", config.integrations.bitbucket),
            ("jira", config.integrations.jira),
            ("confluence", config.integrations.confluence),
        ]
        for (name, service) in services where service.enabled || !service.host.isEmpty {
            lines.append("")
            lines.append("[integrations.\(name)]")
            lines.append("enabled = \(service.enabled)")
            if !service.host.isEmpty {
                lines.append("host = \"\(service.host)\"")
            }
            if !service.user.isEmpty {
                lines.append("user = \"\(service.user)\"")
            }
        }
        if !config.workspaceMonitors.isEmpty {
            lines.append("")
            lines.append("[workspace-monitors]")
            for (workspace, monitor) in config.workspaceMonitors.sorted(by: { $0.key < $1.key }) {
                lines.append("\(workspace) = \"\(monitor)\"")
            }
        }
        if !config.appWorkspaces.isEmpty {
            lines.append("")
            lines.append("[workspace-apps]")
            for (app, workspace) in config.appWorkspaces.sorted(by: { $0.key < $1.key }) {
                lines.append("\"\(app)\" = \(workspace)")
            }
        }
        // Binding-merge: configs whose bindings/modes match the defaults stay
        // implicit, so future default improvements reach them automatically.
        if config.bindings != PanewrightConfig.default.bindings {
            for binding in config.bindings {
                lines.append("")
                lines.append("[[binding]]")
                lines.append("key = \"\(binding.key)\"")
                lines.append("action = \"\(chainString(binding.actions))\"")
            }
        }
        if config.modes != PanewrightConfig.default.modes {
            for mode in config.modes {
                lines.append("")
                lines.append("[[mode]]")
                lines.append("name = \"\(mode.name)\"")
                for binding in mode.bindings {
                    lines.append("")
                    lines.append("[[mode.binding]]")
                    lines.append("key = \"\(binding.key)\"")
                    lines.append("action = \"\(chainString(binding.actions))\"")
                }
            }
        }
        return lines.joined(separator: "\n") + "\n"
    }

    public static func chainString(_ actions: [PanewrightConfig.Action]) -> String {
        actions.map(actionString).joined(separator: "; ")
    }

    public static func actionString(_ action: PanewrightConfig.Action) -> String {
        switch action {
        case .workspace(let n): "workspace \(n)"
        case .moveToWorkspace(let n): "move to workspace \(n)"
        case .focus(let direction): "focus \(direction.rawValue)"
        case .move(let direction): "move \(direction.rawValue)"
        case .layoutTiles: "layout tiles"
        case .layoutAccordion: "layout accordion"
        case .fullscreen: "fullscreen"
        case .toggleFloating: "floating toggle"
        case .focusMonitor(let target): "focus monitor \(target.rawValue)"
        case .moveToMonitor(let target): "move to monitor \(target.rawValue)"
        case .resize(let dimension, let delta): "resize \(dimension.rawValue) \(delta)"
        case .joinWith(let direction): "join \(direction.rawValue)"
        case .flattenWorkspace: "flatten"
        case .enterMode(let name): "mode \(name)"
        case .exec(let command): "exec \(command)"
        case .close: "close"
        case .scratchpadShow: "scratchpad show"
        case .scratchpadMove: "move scratchpad"
        case .workspaceBackAndForth: "workspace back_and_forth"
        case .todoAdd: "todo add"
        case .pillWindow: "pill window"
        case .help: "help"
        case .balanceSizes: "balance"
        case .nativeFullscreen: "fullscreen native"
        case .minimize: "minimize"
        case .closeOthers: "close others"
        case .focusBackAndForth: "focus back_and_forth"
        case .moveWorkspaceToMonitor(let target): "move workspace to monitor \(target.rawValue)"
        }
    }
}
