/// Renders a ``PanewrightConfig`` back into `panewright.toml` syntax — the
/// inverse of ``ConfigParser``. Used by the i3 importer (and eventually the
/// visual editor's save path).
public enum PanewrightConfigSerializer {
    public static func emit(_ config: PanewrightConfig) -> String {
        var lines: [String] = []
        lines.append("# Generated by Panewright.")
        lines.append("modifier = \"\(config.modifier.rawValue)\"")
        if config.modifier == .leader {
            lines.append("leader-key = \"\(config.leaderKey)\"")
        }
        if !config.floatingApps.isEmpty {
            lines.append("floating-apps = [")
            for app in config.floatingApps {
                lines.append("  \"\(app)\",")
            }
            lines.append("]")
        }
        lines.append("")
        lines.append("[gaps]")
        lines.append("inner = \(config.gaps.inner)")
        lines.append("outer = \(config.gaps.outer)")
        lines.append("")
        lines.append("[border]")
        lines.append("enabled = \(config.focusBorder.enabled)")
        lines.append("width = \(config.focusBorder.width)")
        lines.append("active-color = \"\(config.focusBorder.activeColor)\"")
        lines.append("inactive-color = \"\(config.focusBorder.inactiveColor)\"")
        lines.append("")
        lines.append("[bar]")
        lines.append("enabled = \(config.statusBar.enabled)")
        lines.append("theme = \"\(config.statusBar.theme.rawValue)\"")
        if !config.workspaceMonitors.isEmpty {
            lines.append("")
            lines.append("[workspace-monitors]")
            for (workspace, monitor) in config.workspaceMonitors.sorted(by: { $0.key < $1.key }) {
                lines.append("\(workspace) = \"\(monitor)\"")
            }
        }
        for binding in config.bindings {
            lines.append("")
            lines.append("[[binding]]")
            lines.append("key = \"\(binding.key)\"")
            lines.append("action = \"\(chainString(binding.actions))\"")
        }
        for mode in config.modes {
            lines.append("")
            lines.append("[[mode]]")
            lines.append("name = \"\(mode.name)\"")
            for binding in mode.bindings {
                lines.append("")
                lines.append("[[mode.binding]]")
                lines.append("key = \"\(binding.key)\"")
                lines.append("action = \"\(chainString(binding.actions))\"")
            }
        }
        return lines.joined(separator: "\n") + "\n"
    }

    public static func chainString(_ actions: [PanewrightConfig.Action]) -> String {
        actions.map(actionString).joined(separator: "; ")
    }

    public static func actionString(_ action: PanewrightConfig.Action) -> String {
        switch action {
        case .workspace(let n): "workspace \(n)"
        case .moveToWorkspace(let n): "move to workspace \(n)"
        case .focus(let direction): "focus \(direction.rawValue)"
        case .move(let direction): "move \(direction.rawValue)"
        case .layoutTiles: "layout tiles"
        case .layoutAccordion: "layout accordion"
        case .fullscreen: "fullscreen"
        case .toggleFloating: "floating toggle"
        case .focusMonitor(let target): "focus monitor \(target.rawValue)"
        case .moveToMonitor(let target): "move to monitor \(target.rawValue)"
        case .resize(let dimension, let delta): "resize \(dimension.rawValue) \(delta)"
        case .joinWith(let direction): "join \(direction.rawValue)"
        case .flattenWorkspace: "flatten"
        case .enterMode(let name): "mode \(name)"
        case .exec(let command): "exec \(command)"
        case .close: "close"
        }
    }
}
