import Foundation
import Testing

@testable import PanewrightCore

/// Installing Panewright overwrites ~/.config/aerospace and ~/.config/sketchybar
/// from its own templates. For anyone already using those tools that's work
/// they can't get back, so these tests are about not destroying it.
@Suite struct ConfigBackupTests {
    private func temporaryDirectory() throws -> URL {
        let url = FileManager.default.temporaryDirectory
            .appending(path: "panewright-backup-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    @Test func someoneElsesConfigIsKept() throws {
        let root = try temporaryDirectory()
        defer { try? FileManager.default.removeItem(at: root) }
        let config = root.appending(path: "aerospace.toml")
        try "# my careful setup\ngaps.inner.horizontal = 12\n".write(
            to: config, atomically: true, encoding: .utf8)

        let saved = try #require(ConfigBackup.preserve(config, into: root.appending(path: "b")))
        #expect(try String(contentsOf: saved, encoding: .utf8).contains("my careful setup"))
    }

    @Test func ourOwnOutputIsNotArchivedOverAndOver() throws {
        // Every apply rewrites these files. Without recognising our own
        // output, a week of ordinary use would bury the one backup that
        // matters under hundreds of copies of our template.
        let root = try temporaryDirectory()
        defer { try? FileManager.default.removeItem(at: root) }
        let config = root.appending(path: "aerospace.toml")
        try "# Generated by Panewright — do not edit by hand.\nmode.main = {}\n".write(
            to: config, atomically: true, encoding: .utf8)

        #expect(ConfigBackup.preserve(config, into: root.appending(path: "b")) == nil)
    }

    @Test func aMissingFileIsNothingToPreserve() throws {
        let root = try temporaryDirectory()
        defer { try? FileManager.default.removeItem(at: root) }
        let absent = root.appending(path: "not-there.toml")
        #expect(!ConfigBackup.isForeign(absent))
        #expect(ConfigBackup.preserve(absent, into: root.appending(path: "b")) == nil)
    }

    @Test func aDirectoryOfPluginsIsKeptWithItsShape() throws {
        // ~/.config/sketchybar is a tree, and someone's own plugins sit in the
        // same folders ours go into. The paths have to survive so the backup
        // can be copied back.
        let root = try temporaryDirectory()
        defer { try? FileManager.default.removeItem(at: root) }
        let bar = root.appending(path: "sketchybar")
        let plugins = bar.appending(path: "plugins")
        try FileManager.default.createDirectory(at: plugins, withIntermediateDirectories: true)
        try "#!/bin/bash\n# my bar\n".write(
            to: bar.appending(path: "sketchybarrc"), atomically: true, encoding: .utf8)
        try "#!/bin/bash\necho custom\n".write(
            to: plugins.appending(path: "mine.sh"), atomically: true, encoding: .utf8)
        try "# Generated by Panewright. ours\n".write(
            to: plugins.appending(path: "panewright_mode.sh"), atomically: true, encoding: .utf8)

        let saved = ConfigBackup.preserveContents(of: bar, into: root.appending(path: "b"))
        let names = saved.map(\.lastPathComponent).sorted()
        // Theirs kept, ours skipped.
        #expect(names == ["mine.sh", "sketchybarrc"])
        #expect(saved.contains { $0.path.contains("/plugins/mine.sh") })
    }

    @Test func aSecondBackupNeverOverwritesTheFirst() throws {
        // Two runs inside the same second must not have the later one destroy
        // the earlier — the entire promise here is that nothing is lost.
        let root = try temporaryDirectory()
        defer { try? FileManager.default.removeItem(at: root) }
        let backups = root.appending(path: "b")
        let config = root.appending(path: "aerospace.toml")
        let moment = Date()

        try "first".write(to: config, atomically: true, encoding: .utf8)
        let one = try #require(ConfigBackup.preserve(config, into: backups, now: moment))
        try "second".write(to: config, atomically: true, encoding: .utf8)
        let two = try #require(ConfigBackup.preserve(config, into: backups, now: moment))

        #expect(one != two)
        #expect(try String(contentsOf: one, encoding: .utf8) == "first")
        #expect(try String(contentsOf: two, encoding: .utf8) == "second")
    }

    @Test func backupsAreGroupedByWhenTheyHappened() {
        let a = ConfigBackup.folder(in: URL(filePath: "/tmp/b"), at: Date(timeIntervalSince1970: 0))
        let b = ConfigBackup.folder(
            in: URL(filePath: "/tmp/b"), at: Date(timeIntervalSince1970: 86400))
        #expect(a != b)
        // Sortable by name, so the newest is obvious in Finder.
        #expect(a.lastPathComponent < b.lastPathComponent)
    }
}
