import Foundation

/// Preserves configuration Panewright is about to replace.
///
/// Panewright writes `~/.config/aerospace/aerospace.toml` and the whole
/// `~/.config/sketchybar` directory from its own templates. Someone who
/// already uses either of those tools has spent real time on those files, and
/// installing Panewright would previously destroy them without a word.
///
/// The rule is: back up anything Panewright didn't write, once, before the
/// first time it's replaced. Our own output carries a "Generated by
/// Panewright" header, so a file bearing it is ours to overwrite freely —
/// otherwise every apply would archive another copy of our own template and
/// the backup directory would become useless noise.
public enum ConfigBackup {
    /// Header that marks a file as Panewright's own output.
    static let marker = "Generated by Panewright"

    /// Does this path hold something the user wrote?
    ///
    /// A missing file isn't foreign — there's nothing to lose. A file we
    /// generated isn't either. Anything else is theirs.
    public static func isForeign(_ url: URL) -> Bool {
        guard let contents = try? String(contentsOf: url, encoding: .utf8) else {
            // Unreadable or absent. An unreadable file that exists is treated
            // as foreign: better a redundant copy than a destroyed one.
            return FileManager.default.fileExists(atPath: url.path)
        }
        return !contents.contains(marker)
    }

    /// Copy `url` into a timestamped folder, if it's something the user wrote.
    ///
    /// Returns where it went, or nil when there was nothing worth keeping.
    /// Best-effort by design: failing to archive a file must not stop
    /// Panewright configuring itself, since that would leave someone with a
    /// half-set-up environment and no way forward.
    @discardableResult
    public static func preserve(
        _ url: URL, into directory: URL, now: Date = Date()
    ) -> URL? {
        guard isForeign(url) else { return nil }
        let destination = folder(in: directory, at: now)
        do {
            try FileManager.default.createDirectory(
                at: destination, withIntermediateDirectories: true)
            let target = uniqueDestination(destination.appending(path: url.lastPathComponent))
            if FileManager.default.fileExists(atPath: url.path) {
                try FileManager.default.copyItem(at: url, to: target)
                return target
            }
        } catch {
            return nil
        }
        return nil
    }

    /// Copy every foreign file in a directory tree.
    ///
    /// Used for `~/.config/sketchybar`, which is a directory of scripts rather
    /// than a single file, and where a user's plugins sit alongside ours.
    @discardableResult
    public static func preserveContents(
        of source: URL, into directory: URL, now: Date = Date()
    ) -> [URL] {
        let manager = FileManager.default
        guard let walker = manager.enumerator(atPath: source.path) else { return [] }
        var saved: [URL] = []
        for case let relative as String in walker {
            let file = source.appending(path: relative)
            var isDirectory: ObjCBool = false
            guard manager.fileExists(atPath: file.path, isDirectory: &isDirectory),
                !isDirectory.boolValue, isForeign(file)
            else { continue }
            let destination = folder(in: directory, at: now)
                .appending(path: source.lastPathComponent)
                .appending(path: relative)
            do {
                try manager.createDirectory(
                    at: destination.deletingLastPathComponent(),
                    withIntermediateDirectories: true)
                let target = uniqueDestination(destination)
                try manager.copyItem(at: file, to: target)
                saved.append(target)
            } catch {
                continue
            }
        }
        return saved
    }

    /// One folder per run, named so the order is obvious in Finder.
    static func folder(in directory: URL, at date: Date) -> URL {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd-HHmmss"
        formatter.timeZone = .current
        return directory.appending(path: formatter.string(from: date))
    }

    /// Never overwrite an existing backup — the whole point is that nothing
    /// is lost, and two runs in the same second must not collide.
    private static func uniqueDestination(_ url: URL) -> URL {
        guard FileManager.default.fileExists(atPath: url.path) else { return url }
        let base = url.deletingPathExtension().lastPathComponent
        let ext = url.pathExtension
        for suffix in 2...100 {
            let candidate = url.deletingLastPathComponent()
                .appending(path: ext.isEmpty ? "\(base)-\(suffix)" : "\(base)-\(suffix).\(ext)")
            if !FileManager.default.fileExists(atPath: candidate.path) { return candidate }
        }
        return url
    }
}
