/// Renders a ``PanewrightConfig`` as an `aerospace.toml` that Panewright owns
/// and AeroSpace consumes.
public enum AeroSpaceConfigEmitter {
    public static func emit(_ config: PanewrightConfig) -> String {
        var lines: [String] = []
        lines.append("# Generated by Panewright — do not edit by hand.")
        lines.append("# Edit panewright.toml (or use the Panewright app) instead.")
        lines.append("config-version = 2")
        lines.append("start-at-login = false")
        lines.append("")
        // i3 mental model: numbered workspaces always exist, even when empty.
        let workspaces = workspaceNumbers(in: config.bindings)
        if !workspaces.isEmpty {
            let list = workspaces.map { "'\($0)'" }.joined(separator: ", ")
            lines.append("persistent-workspaces = [\(list)]")
            lines.append("")
        }
        lines.append("[gaps]")
        lines.append("inner.horizontal = \(config.gaps.inner)")
        lines.append("inner.vertical = \(config.gaps.inner)")
        for edge in ["left", "bottom", "top", "right"] {
            lines.append("outer.\(edge) = \(config.gaps.outer)")
        }
        lines.append("")
        lines.append("[mode.main.binding]")
        for binding in config.bindings {
            let combo = keyCombo(modifier: config.modifier, key: binding.key)
            lines.append("\(combo) = '\(command(for: binding.action))'")
        }
        return lines.joined(separator: "\n") + "\n"
    }

    /// AeroSpace key syntax: modifiers joined by `-`, key last (`alt-shift-1`).
    ///
    /// The hyper base is Cmd+Opt+Ctrl *without* Shift so that i3-style
    /// `$mod+Shift+…` chords remain distinguishable from plain `$mod+…`.
    static func keyCombo(modifier: PanewrightConfig.Modifier, key: String) -> String {
        let base =
            switch modifier {
            case .hyper: "cmd-alt-ctrl"
            case .alt: "alt"
            case .cmd: "cmd"
            }
        if key.hasPrefix("shift-") {
            return "\(base)-shift-\(key.dropFirst("shift-".count))"
        }
        return "\(base)-\(key)"
    }

    static func workspaceNumbers(in bindings: [PanewrightConfig.Binding]) -> [Int] {
        var numbers: Set<Int> = []
        for binding in bindings {
            switch binding.action {
            case .workspace(let n), .moveToWorkspace(let n):
                numbers.insert(n)
            case .focus, .move:
                break
            }
        }
        return numbers.sorted()
    }

    static func command(for action: PanewrightConfig.Action) -> String {
        switch action {
        case .workspace(let n): "workspace \(n)"
        case .moveToWorkspace(let n): "move-node-to-workspace \(n)"
        case .focus(let direction): "focus \(direction.rawValue)"
        case .move(let direction): "move \(direction.rawValue)"
        }
    }
}
