/// Renders a ``PanewrightConfig`` as an `aerospace.toml` that Panewright owns
/// and AeroSpace consumes.
public enum AeroSpaceConfigEmitter {
    public static func emit(_ config: PanewrightConfig) -> String {
        var lines: [String] = []
        lines.append("# Generated by Panewright — do not edit by hand.")
        lines.append("# Edit panewright.toml (or use the Panewright app) instead.")
        lines.append("config-version = 2")
        lines.append("start-at-login = false")
        lines.append("")
        // i3 split behavior: workspaces come up tiling, nested splits alternate
        // orientation, and redundant single-child containers are flattened.
        lines.append("default-root-container-layout = 'tiles'")
        lines.append("enable-normalization-flatten-containers = true")
        lines.append("enable-normalization-opposite-orientation-for-nested-containers = true")
        lines.append("")
        // i3 mental model: numbered workspaces always exist, even when empty.
        let workspaces = workspaceNumbers(in: config.bindings)
        if !workspaces.isEmpty {
            let list = workspaces.map { "'\($0)'" }.joined(separator: ", ")
            lines.append("persistent-workspaces = [\(list)]")
            lines.append("")
        }
        if !config.workspaceMonitors.isEmpty {
            lines.append("[workspace-to-monitor-force-assignment]")
            for (workspace, monitor) in config.workspaceMonitors.sorted(by: { $0.key < $1.key }) {
                lines.append("\(workspace) = '\(monitor)'")
            }
            lines.append("")
        }
        for appId in config.floatingApps {
            lines.append("[[on-window-detected]]")
            lines.append("if.app-id = '\(appId)'")
            lines.append("run = 'layout floating'")
            lines.append("")
        }
        lines.append("[gaps]")
        lines.append("inner.horizontal = \(config.gaps.inner)")
        lines.append("inner.vertical = \(config.gaps.inner)")
        for edge in ["left", "bottom", "top", "right"] {
            lines.append("outer.\(edge) = \(config.gaps.outer)")
        }
        lines.append("")
        lines.append("[mode.main.binding]")
        for binding in config.bindings {
            let combo = keyCombo(modifier: config.modifier, key: binding.key)
            lines.append("\(combo) = \(bindingValue(binding))")
        }
        // Mode bindings are bare keys — that's the point of a mode.
        for mode in config.modes {
            lines.append("")
            lines.append("[mode.\(mode.name).binding]")
            for binding in mode.bindings {
                lines.append("\(binding.key) = \(bindingValue(binding))")
            }
        }
        return lines.joined(separator: "\n") + "\n"
    }

    /// AeroSpace key syntax: modifiers joined by `-`, key last (`alt-shift-1`).
    ///
    /// The hyper base is Cmd+Opt+Ctrl *without* Shift so that i3-style
    /// `$mod+Shift+…` chords remain distinguishable from plain `$mod+…`.
    static func keyCombo(modifier: PanewrightConfig.Modifier, key: String) -> String {
        let base =
            switch modifier {
            case .hyper: "cmd-alt-ctrl"
            case .alt: "alt"
            case .cmd: "cmd"
            }
        if key.hasPrefix("shift-") {
            return "\(base)-shift-\(key.dropFirst("shift-".count))"
        }
        return "\(base)-\(key)"
    }

    static func workspaceNumbers(in bindings: [PanewrightConfig.Binding]) -> [Int] {
        var numbers: Set<Int> = []
        for action in bindings.flatMap(\.actions) {
            switch action {
            case .workspace(let n), .moveToWorkspace(let n):
                numbers.insert(n)
            default:
                break
            }
        }
        return numbers.sorted()
    }

    /// A binding's TOML value: a single command as a string, a chain as an array.
    static func bindingValue(_ binding: PanewrightConfig.Binding) -> String {
        let commands = binding.actions.map { "'\(command(for: $0))'" }
        return commands.count == 1 ? commands[0] : "[\(commands.joined(separator: ", "))]"
    }

    static func command(for action: PanewrightConfig.Action) -> String {
        switch action {
        case .workspace(let n): "workspace \(n)"
        case .moveToWorkspace(let n): "move-node-to-workspace \(n)"
        case .focus(let direction): "focus \(direction.rawValue)"
        case .move(let direction): "move \(direction.rawValue)"
        case .layoutTiles: "layout tiles horizontal vertical"
        case .layoutAccordion: "layout accordion horizontal vertical"
        case .fullscreen: "fullscreen"
        case .toggleFloating: "layout floating tiling"
        case .focusMonitor(let target): "focus-monitor \(target.rawValue)"
        case .moveToMonitor(let target): "move-node-to-monitor \(target.rawValue)"
        case .resize(let dimension, let delta):
            "resize \(dimension.rawValue) \(delta >= 0 ? "+\(delta)" : "\(delta)")"
        case .joinWith(let direction): "join-with \(direction.rawValue)"
        case .enterMode(let name): "mode \(name)"
        case .exec(let command): "exec-and-forget \(command)"
        }
    }
}
