/// Renders a ``PanewrightConfig`` as an `aerospace.toml` that Panewright owns
/// and AeroSpace consumes.
public enum AeroSpaceConfigEmitter {
    public static func emit(_ config: PanewrightConfig) -> String {
        var lines: [String] = []
        lines.append("# Generated by Panewright — do not edit by hand.")
        lines.append("# Edit panewright.toml (or use the Panewright app) instead.")
        lines.append("config-version = 2")
        lines.append("start-at-login = false")
        if config.statusBar.enabled || config.workspaceChangedHook != nil {
            // One dispatch script serves the bar and the user's hook.
            // NB: the array form is execv-style — only `bash -c <string>`
            // gets shell expansion of $HOME.
            lines.append(
                "exec-on-workspace-change = ['/bin/bash', '-c', '\"$HOME\"/.config/panewright/scripts/on-workspace-change.sh']"
            )
        }
        // NB: no on-focus-changed trigger. Focus changes arrive in bursts
        // (system permission dialogs especially), and the concurrent repaints
        // they spawned kept tripping a heap-corruption abort inside SketchyBar.
        // Pill occupancy freshness comes from the driver's update_freq poll.
        lines.append("")
        // i3 split behavior: workspaces come up tiling, nested splits alternate
        // orientation, and redundant single-child containers are flattened.
        lines.append("default-root-container-layout = 'tiles'")
        lines.append("enable-normalization-flatten-containers = true")
        lines.append("enable-normalization-opposite-orientation-for-nested-containers = true")
        lines.append("")
        // i3 mental model: numbered workspaces always exist, even when empty.
        let workspaces = workspaceNumbers(in: config.bindings)
        if !workspaces.isEmpty {
            let list = workspaces.map { "'\($0)'" }.joined(separator: ", ")
            lines.append("persistent-workspaces = [\(list)]")
            lines.append("")
        }
        if !config.workspaceMonitors.isEmpty {
            lines.append("[workspace-to-monitor-force-assignment]")
            for (workspace, monitor) in config.workspaceMonitors.sorted(by: { $0.key < $1.key }) {
                lines.append("\(workspace) = '\(monitor)'")
            }
            lines.append("")
        }
        // Skip junk entries (an empty row in the editor, a stray dash) —
        // they'd emit rules that match nothing.
        for appId in config.floatingApps where appId.contains(".") {
            lines.append("[[on-window-detected]]")
            lines.append("if.app-id = '\(appId)'")
            lines.append("run = 'layout floating'")
            lines.append("")
        }
        // i3's assign: apps that always open on a given workspace.
        for (appId, workspace) in config.appWorkspaces.sorted(by: { $0.key < $1.key }) {
            lines.append("[[on-window-detected]]")
            lines.append("if.app-id = '\(appId)'")
            lines.append("run = 'move-node-to-workspace \(workspace)'")
            lines.append("")
        }
        lines.append("[gaps]")
        lines.append("inner.horizontal = \(config.gaps.inner)")
        lines.append("inner.vertical = \(config.gaps.inner)")
        // The status bar sits at the bottom, so tiles reserve that strip;
        // without it the normal edge applies.
        let bottomGap =
            config.gaps.outer
            + (config.statusBar.enabled
                ? SketchyBarConfigEmitter.reservedTopGap(for: config.statusBar.theme) : 0)
        lines.append("outer.left = \(config.gaps.outer)")
        lines.append("outer.top = \(config.gaps.outer)")
        lines.append("outer.bottom = \(bottomGap)")
        lines.append("outer.right = \(config.gaps.outer)")
        lines.append("")
        let barEnabled = config.statusBar.enabled
        lines.append("[mode.main.binding]")
        if config.modifier == .leader {
            // tmux-style: the prefix is the only global binding; commands are
            // bare keys in a one-shot mode that falls back to main.
            let enterPanewright =
                barEnabled
                ? "['mode panewright', '\(modeTrigger("panewright"))']"
                : "'mode panewright'"
            lines.append("\(config.leaderKey) = \(enterPanewright)")
            lines.append("")
            lines.append("[mode.panewright.binding]")
            let escape =
                barEnabled
                ? "['mode main', '\(modeTrigger("main"))']" : "'mode main'"
            lines.append("esc = \(escape)")
            for binding in config.bindings {
                lines.append(
                    "\(binding.key) = \(leaderBindingValue(binding, statusBarEnabled: barEnabled))"
                )
            }
        } else {
            for binding in config.bindings {
                let combo = keyCombo(modifier: config.modifier, key: binding.key)
                lines.append("\(combo) = \(bindingValue(binding, statusBarEnabled: barEnabled))")
            }
        }
        // Mode bindings are bare keys — that's the point of a mode.
        for mode in config.modes {
            lines.append("")
            lines.append("[mode.\(mode.name).binding]")
            for binding in mode.bindings {
                lines.append("\(binding.key) = \(bindingValue(binding, statusBarEnabled: barEnabled))")
            }
        }
        return lines.joined(separator: "\n") + "\n"
    }

    /// AeroSpace key syntax: modifiers joined by `-`, key last (`alt-shift-1`).
    ///
    /// The hyper base is Cmd+Opt+Ctrl *without* Shift so that i3-style
    /// `$mod+Shift+…` chords remain distinguishable from plain `$mod+…`.
    static func keyCombo(modifier: PanewrightConfig.Modifier, key: String) -> String {
        // Leader style never chords: bindings live bare inside the
        // panewright mode, so a combo request passes the key through.
        if modifier == .leader {
            return key
        }
        let base =
            switch modifier {
            case .hyper: "cmd-alt-ctrl"
            case .alt: "alt"
            case .cmd: "cmd"
            case .ctrl: "ctrl"
            case .ctrlAlt: "ctrl-alt"
            case .ctrlCmd: "ctrl-cmd"
            case .leader: ""
            }
        if key.hasPrefix("shift-") {
            return "\(base)-shift-\(key.dropFirst("shift-".count))"
        }
        return "\(base)-\(key)"
    }

    static func workspaceNumbers(in bindings: [PanewrightConfig.Binding]) -> [Int] {
        var numbers: Set<Int> = []
        for action in bindings.flatMap(\.actions) {
            switch action {
            case .workspace(let n), .moveToWorkspace(let n):
                numbers.insert(n)
            default:
                break
            }
        }
        // Keyboard-row order: 0 sits after 9, not before 1.
        return numbers.sorted { lhs, rhs in
            (lhs == 0 ? 10 : lhs) < (rhs == 0 ? 10 : rhs)
        }
    }

    /// The status bar can't observe mode changes, so every mode switch pings
    /// it explicitly as part of the binding's command chain.
    static func modeTrigger(_ name: String) -> String {
        "exec-and-forget /opt/homebrew/bin/sketchybar --trigger panewright_mode MODE=\(name)"
    }

    /// A binding's TOML value: a single command as a string, a chain as an array.
    static func bindingValue(
        _ binding: PanewrightConfig.Binding, statusBarEnabled: Bool = false
    ) -> String {
        var commands: [String] = []
        for action in binding.actions {
            for command in Self.commands(for: action) {
                commands.append("'\(command)'")
            }
            if statusBarEnabled, case .enterMode(let name) = action {
                commands.append("'\(modeTrigger(name))'")
            }
        }
        return commands.count == 1 ? commands[0] : "[\(commands.joined(separator: ", "))]"
    }

    /// Most actions are one AeroSpace command; a few expand to several.
    static func commands(for action: PanewrightConfig.Action) -> [String] {
        switch action {
        case .scratchpadMove:
            // Stash: float (i3 scratchpad windows are floating) and park on
            // the hidden "S" workspace (letters never appear in the bar).
            ["layout floating", "move-node-to-workspace S"]
        default:
            [command(for: action)]
        }
    }

    /// Leader-mode value: one-shot — every chain falls back to main unless it
    /// already ends by entering another mode.
    static func leaderBindingValue(
        _ binding: PanewrightConfig.Binding, statusBarEnabled: Bool = false
    ) -> String {
        var actions = binding.actions
        let endsInModeChange: Bool
        if let last = actions.last, case .enterMode = last {
            endsInModeChange = true
        } else {
            endsInModeChange = false
        }
        if !endsInModeChange {
            actions.append(.enterMode("main"))
        }
        return bindingValue(
            PanewrightConfig.Binding(key: binding.key, actions: actions),
            statusBarEnabled: statusBarEnabled)
    }

    static func command(for action: PanewrightConfig.Action) -> String {
        switch action {
        // summon-workspace, not workspace: i3-style multi-monitor semantics.
        // If the workspace is showing on another monitor, $mod+N pulls it to
        // the focused monitor rather than yanking focus across the room; on a
        // single monitor it behaves exactly like `workspace`.
        case .workspace(let n): "summon-workspace \(n)"
        case .moveToWorkspace(let n): "move-node-to-workspace \(n)"
        case .focus(let direction): "focus \(direction.rawValue)"
        case .move(let direction): "move \(direction.rawValue)"
        case .layoutTiles: "layout tiles horizontal vertical"
        case .layoutAccordion: "layout accordion horizontal vertical"
        case .fullscreen: "fullscreen"
        case .toggleFloating: "layout floating tiling"
        case .focusMonitor(let target): "focus-monitor \(target.rawValue)"
        case .moveToMonitor(let target): "move-node-to-monitor \(target.rawValue)"
        case .resize(let dimension, let delta):
            "resize \(dimension.rawValue) \(delta >= 0 ? "+\(delta)" : "\(delta)")"
        case .joinWith(let direction): "join-with \(direction.rawValue)"
        case .flattenWorkspace: "flatten-workspace-tree"
        case .enterMode(let name): "mode \(name)"
        case .exec(let command): "exec-and-forget \(command)"
        case .close: "close"
        case .workspaceBackAndForth: "workspace-back-and-forth"
        case .todoAdd:
            "exec-and-forget /bin/bash \"$HOME/.config/panewright/scripts/todo-add.sh\""
        case .pillWindow:
            "exec-and-forget /bin/bash \"$HOME/.config/panewright/scripts/pill-window.sh\""
        case .help:
            "exec-and-forget open panewright://help"
        case .scratchpadShow:
            "exec-and-forget /bin/bash \"$HOME/.config/panewright/scripts/scratchpad-show.sh\""
        case .scratchpadMove:
            // Multi-command action; see commands(for:). This single-command
            // fallback covers direct callers.
            "move-node-to-workspace S"
        }
    }
}
