/// Generates SketchyBar's config script and plugins from a PanewrightConfig.
/// Two aesthetics, one toggle: native (SF Pro, vibrancy, floating pill) and
/// technical (monospace, square, solid). The accent color follows the focus
/// border so the whole system reads as one theme.
public enum SketchyBarConfigEmitter {
    public struct Files: Equatable, Sendable {
        public var sketchybarrc: String
        public var workspacesPlugin: String
        public var modePlugin: String
        public var frontAppPlugin: String
        public var todoPlugin: String
        public var integrationsPlugin: String
        public var reorderPlugin: String
        public var pillsPlugin: String
        public var systemPlugin: String
        public var widgetsPlugin: String
        public var tooltipPlugin: String
    }

    private struct Palette {
        let barProps: String
        let font: String
        let text: String
        let dim: String
    }

    private static func palette(for theme: PanewrightConfig.StatusBar.Theme) -> Palette {
        switch theme {
        case .native:
            Palette(
                barProps:
                    "height=30 corner_radius=9 margin=8 y_offset=5 blur_radius=30 color=0x2c000000",
                font: "SF Pro:Semibold:13.0",
                text: "0xffffffff",
                dim: "0x80ffffff")
        case .technical:
            Palette(
                barProps:
                    "height=26 corner_radius=0 margin=0 y_offset=0 blur_radius=0 color=0xf016161e",
                font: "SF Mono:Bold:12.0",
                text: "0xffc0caf5",
                dim: "0x66c0caf5")
        }
    }

    /// Vertical space tiles must reserve so the bar isn't covered by windows:
    /// bar height + y-offset + breathing room. The AeroSpace emitter adds
    /// this to outer.top whenever the bar is enabled.
    public static func reservedTopGap(for theme: PanewrightConfig.StatusBar.Theme) -> Int {
        switch theme {
        case .native: 40  // height 30 + y_offset 5 + 5 breathing
        case .technical: 32  // height 26 + 6 breathing
        }
    }

    public static func emit(_ config: PanewrightConfig) throws -> Files {
        let accent = String(
            format: "0x%08x", try ColorHex.argb(fromCSSHex: config.focusBorder.activeColor))
        // The workspace highlight defaults to the border accent (one color, one
        // system) but can be set independently.
        let barAccent = try config.statusBar.accentColor.map {
            String(format: "0x%08x", try ColorHex.argb(fromCSSHex: $0))
        } ?? accent
        let palette = palette(for: config.statusBar.theme)
        let workspaces = AeroSpaceConfigEmitter.workspaceNumbers(in: config.bindings)
        let workspaceList = workspaces.map(String.init).joined(separator: " ")
        // Per-display item names, display outer so each monitor's strip stays
        // contiguous. Hidden items keep their slot but don't render. Each
        // display leads with its monitor badge (M1/M2/M3).
        let spaceOrder = (1...4)
            .flatMap { d in ["monitor.\(d)"] + workspaces.map { "space.\(d).\($0)" } }
            .joined(separator: " ")

        let rc = """
            #!/bin/bash
            export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
            # Generated by Panewright — do not edit by hand.
            # Edit panewright.toml (or use the Panewright app) instead.
            PLUGINS="$HOME/.config/sketchybar/plugins"
            SCRIPTS_DIR="$HOME/.config/panewright/scripts"
            BAR=/opt/homebrew/bin/sketchybar

            # Bottom bar: the top edge is the native menu bar's auto-reveal
            # zone, which fought our drag-to-park and workspace clicks. The
            # bottom edge triggers nothing, needs no menu-bar hiding, and is
            # consistent across a notched primary and flat externals.
            $BAR --bar position=bottom sticky=on \(palette.barProps)
            $BAR --default icon.font="\(palette.font)" label.font="\(palette.font)" \\
                icon.color=\(palette.text) label.color=\(palette.text) \\
                padding_left=4 padding_right=4

            $BAR --add event aerospace_workspace_change
            $BAR --add event panewright_mode
            $BAR --add event panewright_todo
            $BAR --add event panewright_integrations
            $BAR --add event panewright_pills
            $BAR --add event panewright_widgets

            \(config.pills.enabled ? """
            $BAR --add item pills left \\
              --set pills update_freq=90 drawing=off \\
                script="$PLUGINS/panewright_pills.sh" \\
              --subscribe pills panewright_pills
            """ : "")

            # One strip per display (associated_display). Each item shows only
            # when its workspace lives on that display's monitor. Displays
            # beyond the actual count never render. The M-badge leads each
            # strip, naming the AeroSpace monitor (the number monitor commands
            # refer to).
            for did in 1 2 3 4; do
              $BAR --add item monitor.$did left \\
                --set monitor.$did associated_display=$did label="" drawing=off \\
                  label.color=\(palette.dim) label.padding_left=8 label.padding_right=2
              for sid in \(workspaceList); do
                $BAR --add item space.$did.$sid left \\
                  --set space.$did.$sid associated_display=$did label="$sid" drawing=off \\
                    label.padding_left=8 label.padding_right=8 \\
                    background.corner_radius=6 background.height=20 background.drawing=off \\
                    click_script="$SCRIPTS_DIR/workspace-select.sh $did $sid"
              done
            done

            # A single hidden driver repaints every strip in one batched call.
            # Subscribing each pill individually would fork one process (and two
            # AeroSpace queries) per pill per event — a stampede that has
            # crashed SketchyBar. One process, one query per display instead.
            # update_freq keeps occupancy fresh (a window moved to a background
            # workspace) without an on-focus-changed trigger — focus changes
            # burst around system dialogs and the resulting concurrent repaints
            # crashed SketchyBar. Workspace switches still repaint instantly
            # via the event.
            $BAR --add item spaces_driver left \\
              --set spaces_driver drawing=off update_freq=2 \\
                script="$PLUGINS/panewright_workspaces.sh" \\
              --subscribe spaces_driver aerospace_workspace_change

            $BAR --add item mode left \\
              --set mode label="" label.color=\(accent) \\
                script="$PLUGINS/panewright_mode.sh" \\
              --subscribe mode panewright_mode

            $BAR --add item front_app left \\
              --set front_app script="$PLUGINS/panewright_front_app.sh" \\
              --subscribe front_app front_app_switched

            \(conflictsItem(count: BindingConflicts.rows(in: config).count))
            \(config.modules.systemMonitor ? systemItem(accent: accent, palette: palette) : "")
            \(widgetItems(config.modules, accent: accent, palette: palette))
            \(config.integrations.anyEnabled ? integrationsItem(accent: accent) : "")
            \(config.todo.enabled ? todoItem(accent: accent) : "")
            # Pin the order explicitly: without this, items can shuffle when
            # the bar re-renders (a screenshot or display change is enough).
            $BAR --reorder \(spaceOrder) mode front_app

            $BAR --update
            # AeroSpace may still be starting (any launch order must work) —
            # retry before painting the initial highlight.
            for attempt in $(seq 1 20); do
              FOCUSED="$(/opt/homebrew/bin/aerospace list-workspaces --focused 2>/dev/null)"
              [ -n "$FOCUSED" ] && break
              sleep 0.5
            done
            $BAR --trigger aerospace_workspace_change FOCUSED_WORKSPACE="$FOCUSED"
            \(config.todo.enabled ? "$BAR --trigger panewright_todo" : "")
            \(config.integrations.anyEnabled ? "$BAR --trigger panewright_integrations" : "")
            """

        let workspacesPlugin = """
            #!/bin/bash
            export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
            # Generated by Panewright. Repaints every display's workspace strip
            # in ONE batched sketchybar call.
            #
            # i3-style dynamic pills: draw a workspace only when it lives on that
            # display's monitor AND is either occupied (has windows) or the one
            # currently visible there. Empty, unfocused workspaces vanish; moving
            # a window onto one makes its pill appear.
            BAR="$(command -v sketchybar)"
            A=/opt/homebrew/bin/aerospace
            MAP="$HOME/.config/panewright/monitor-map.tsv"
            ARGS=()
            for did in 1 2 3 4; do
              MON=$(awk -F'\\t' -v d="$did" '$1 == d { print $2 }' "$MAP" 2>/dev/null)
              # No map yet (first boot): assume identity for display 1 so a
              # single-monitor bar still renders before the app writes the map.
              [ -z "$MON" ] && [ ! -f "$MAP" ] && [ "$did" = 1 ] && MON=1
              if [ -z "$MON" ]; then
                ARGS+=(--set "monitor.$did" drawing=off)
                continue
              fi
              # Badge shows the human-facing number (col 3: primary is always
              # M1), while commands keep using the AeroSpace id (col 2).
              LBL=$(awk -F'\\t' -v d="$did" '$1 == d { print $3 }' "$MAP" 2>/dev/null)
              ARGS+=(--set "monitor.$did" drawing=on label="M${LBL:-$MON}")
              VISIBLE=$("$A" list-workspaces --monitor "$MON" --visible 2>/dev/null | tr -d ' ')
              OCCUPIED=$("$A" list-workspaces --monitor "$MON" --empty no 2>/dev/null | tr -d ' ')
              for sid in \(workspaceList); do
                if [ "$sid" = "$VISIBLE" ]; then
                  ARGS+=(--set "space.$did.$sid" drawing=on background.drawing=on \\
                    background.color=\(barAccent) label.color=0xffffffff)
                elif printf '%s\\n' "$OCCUPIED" | grep -qx "$sid"; then
                  ARGS+=(--set "space.$did.$sid" drawing=on background.drawing=off \\
                    label.color=\(palette.dim))
                else
                  ARGS+=(--set "space.$did.$sid" drawing=off)
                fi
              done
            done
            [ ${#ARGS[@]} -gt 0 ] && "$BAR" "${ARGS[@]}"
            """

        let modePlugin = """
            #!/bin/bash
            export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
            # Generated by Panewright. Badge for the active binding mode.
            if [ -z "$MODE" ] || [ "$MODE" = "main" ]; then
              "$(command -v sketchybar)" --set "$NAME" label=""
            else
              "$(command -v sketchybar)" --set "$NAME" label="[$(printf '%s' "$MODE" | tr '[:lower:]' '[:upper:]')]"
            fi
            """

        let frontAppPlugin = """
            #!/bin/bash
            export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
            # Generated by Panewright.
            "$(command -v sketchybar)" --set "$NAME" label="$INFO"
            """

        let todoPlugin = """
            #!/bin/bash
            export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
            # Generated by Panewright. Renders the to-do item and its popup.
            BAR="$(command -v sketchybar)"
            SCRIPTS="$HOME/.config/panewright/scripts"
            PLUGINS_DIR="$HOME/.config/sketchybar/plugins"
            TODO="$HOME/.config/panewright/todo.txt"
            [ -f "$TODO" ] || touch "$TODO"

            # Storage is TSV: title<TAB>notes. Each task becomes its own pill
            # in the bar, growing leftward from the "+" button; click one to
            # open its editor.
            #
            # Incremental, not rebuild: removing and re-adding every pill on
            # each update made the whole bar flicker and visibly resort. Reuse
            # existing items (a --set repaints in place), add or remove only at
            # the tail, batch everything into ONE sketchybar call, and reorder
            # only when the item count actually changed.
            MAX=6
            EXISTING=$("$BAR" --query bar 2>/dev/null | /usr/bin/python3 -c \\
              'import sys,json;print(sum(1 for i in json.load(sys.stdin).get("items",[]) if i.startswith("todo.item.")))' 2>/dev/null)
            EXISTING=${EXISTING:-0}

            ARGS=()
            i=0
            while IFS= read -r line; do
              case "$line" in ""|" ") continue ;; esac
              [ "$i" -ge "$MAX" ] && break
              TITLE=$(printf '%s' "$line" | cut -f1)
              NOTES=$(printf '%s' "$line" | cut -f2- -s)
              SHORT=$(printf '%.18s' "$TITLE")
              [ "${#TITLE}" -gt 18 ] && SHORT="$SHORT…"
              [ -n "$NOTES" ] && SHORT="$SHORT ·"
              [ "$i" -ge "$EXISTING" ] && ARGS+=(--add item todo.item.$i right)
              ARGS+=(--set todo.item.$i label="$SHORT" label.color=\(palette.text) \\
                label.padding_left=8 label.padding_right=8 \\
                background.corner_radius=6 background.height=20 \\
                background.color=0x1affffff background.drawing=on \\
                click_script="$SCRIPTS/todo-edit.sh $((i + 1))")
              i=$((i + 1))
            done < "$TODO"
            j=$i
            while [ "$j" -lt "$EXISTING" ]; do
              ARGS+=(--remove todo.item.$j)
              j=$((j + 1))
            done

            # awk, not `grep -c || echo 0`: grep prints 0 *and* exits 1 when
            # nothing matches, which yields a two-line "count".
            TOTAL=$(awk 'NF' "$TODO" 2>/dev/null | wc -l | tr -d ' ')
            if [ "$TOTAL" -gt "$MAX" ]; then
              ARGS+=(--set todo label="+$((TOTAL - MAX)) more  +")
            else
              ARGS+=(--set todo label="+")
            fi
            [ ${#ARGS[@]} -gt 0 ] && "$BAR" "${ARGS[@]}"
            # One authority for right-side order — only when items came or went.
            [ "$i" -ne "$EXISTING" ] && "$PLUGINS_DIR/panewright_reorder.sh"
            exit 0
            """

        let integrationsPlugin = """
            #!/bin/bash
            export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
            # Generated by Panewright. One pill per enabled service, fed by
            # the status file the app writes: id<TAB>count<TAB>label.
            BAR="$(command -v sketchybar)"
            PLUGINS_DIR="$HOME/.config/sketchybar/plugins"
            STATUS="$HOME/.config/panewright/integrations.status"
            [ -f "$STATUS" ] || exit 0

            # Incremental like the todo plugin: reuse items, one batched call,
            # reorder only when the pill count changed (see there for why).
            EXISTING=$("$BAR" --query bar 2>/dev/null | /usr/bin/python3 -c \\
              'import sys,json;print(sum(1 for i in json.load(sys.stdin).get("items",[]) if i.startswith("integration.")))' 2>/dev/null)
            EXISTING=${EXISTING:-0}
            ARGS=()
            i=0
            while IFS=$'\\t' read -r id count label; do
              [ -z "$id" ] && continue
              COLOR=\(palette.dim)
              [ "${count:-0}" -gt 0 ] 2>/dev/null && COLOR=\(accent)
              # Extra left padding on the first pill separates this group
              # from the to-do pills.
              PAD=8
              [ "$i" -eq 0 ] && PAD=20
              [ "$i" -ge "$EXISTING" ] && ARGS+=(--add item integration.$i right)
              ARGS+=(--set integration.$i label="$label ${count:-0}" label.color="$COLOR" \\
                label.padding_left=$PAD label.padding_right=8 \\
                background.corner_radius=6 background.height=20 \\
                background.color=0x1affffff background.drawing=on \\
                click_script="open 'panewright://integrations/$id'")
              i=$((i + 1))
            done < "$STATUS"
            j=$i
            while [ "$j" -lt "$EXISTING" ]; do
              ARGS+=(--remove integration.$j)
              j=$((j + 1))
            done
            [ ${#ARGS[@]} -gt 0 ] && "$BAR" "${ARGS[@]}"
            [ "$i" -ne "$EXISTING" ] && "$PLUGINS_DIR/panewright_reorder.sh"
            exit 0
            """

        let pillsPlugin = """
            #!/bin/bash
            export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
            # Generated by Panewright. One pill per parked window; click to
            # peek at it, right-click to give it back to the tiling tree.
            BAR="$(command -v sketchybar)"
            A=/opt/homebrew/bin/aerospace
            SCRIPTS="$HOME/.config/panewright/scripts"
            PLUGINS_DIR="$HOME/.config/sketchybar/plugins"
            PILLS="$HOME/.config/panewright/pills.tsv"
            [ -f "$PILLS" ] || touch "$PILLS"

            # Incremental like the todo plugin: reuse items, one batched call,
            # reorder only when the pill count changed (see there for why).
            EXISTING=$("$BAR" --query bar 2>/dev/null | /usr/bin/python3 -c \\
              'import sys,json;print(sum(1 for i in json.load(sys.stdin).get("items",[]) if i.startswith("pill.")))' 2>/dev/null)
            EXISTING=${EXISTING:-0}
            LIVE=$("$A" list-windows --all --format '%{window-id}' 2>/dev/null | tr -d ' ')
            PARKED=$("$A" list-windows --workspace P --format '%{window-id}' 2>/dev/null | tr -d ' ')

            TMP=$(mktemp)
            ARGS=()
            i=0
            while IFS=$'\\t' read -r id app title; do
              [ -z "$id" ] && continue
              # Drop pills whose window has closed.
              printf '%s\\n' "$LIVE" | grep -qx "$id" || continue
              printf '%s\\t%s\\t%s\\n' "$id" "$app" "$title" >> "$TMP"
              [ "$i" -ge 10 ] && continue
              LABEL=$(printf '%.14s' "${app:-window}")
              if printf '%s\\n' "$PARKED" | grep -qx "$id"; then
                COLOR=\(palette.dim); MARK="▸"
              else
                COLOR=\(accent); MARK="▾"
              fi
              [ "$i" -ge "$EXISTING" ] && ARGS+=(--add item pill.$i left)
              ARGS+=(--set pill.$i label="$MARK $LABEL" label.color="$COLOR" \\
                label.padding_left=8 label.padding_right=8 \\
                background.corner_radius=6 background.height=20 \\
                background.color=0x1affffff background.drawing=on \\
                click_script="if [ \\"\\$BUTTON\\" = \\"right\\" ]; then $SCRIPTS/pill-release.sh $id; else $SCRIPTS/pill-toggle.sh $id; fi")
              i=$((i + 1))
            done < "$PILLS"
            mv "$TMP" "$PILLS"
            j=$i
            while [ "$j" -lt "$EXISTING" ]; do
              ARGS+=(--remove pill.$j)
              j=$((j + 1))
            done
            [ ${#ARGS[@]} -gt 0 ] && "$BAR" "${ARGS[@]}"
            [ "$i" -ne "$EXISTING" ] && "$PLUGINS_DIR/panewright_reorder.sh"
            exit 0
            """

        let systemPlugin = """
            #!/bin/bash
            export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
            # Generated by Panewright. Polls CPU/memory, feeds the two graphs,
            # and fills the perf-panel popup. All no-sudo, no-SIP.
            BAR="$(command -v sketchybar)"
            ENABLED="$HOME/.config/panewright/.widgets-enabled"
            # Respect the runtime toggle like every other widget, so turning
            # this off in the picker hides it without rebuilding the bar.
            if ! grep -qx "system-monitor" "$ENABLED" 2>/dev/null; then
              "$BAR" --set sys drawing=off \\
                     --set sys.cpu.graph drawing=off --set sys.mem.graph drawing=off
              exit 0
            fi
            "$BAR" --set sys drawing=on

            # CPU: top's second sample is the accurate instantaneous one.
            IDLE=$(top -l 2 -n 0 -s 1 2>/dev/null | awk '/CPU usage/{i=$7} END{gsub("%","",i); print i}')
            [ -z "$IDLE" ] && IDLE=100
            CPU=$(awk -v i="$IDLE" 'BEGIN{printf "%.0f", 100 - i}')

            # Memory: used physical vs. hardware total.
            TOTAL=$(sysctl -n hw.memsize 2>/dev/null)
            PAGE=$(sysctl -n hw.pagesize 2>/dev/null)
            USEDP=$(vm_stat 2>/dev/null | awk -v p="$PAGE" '
              /Pages active/{a=$3} /Pages wired/{w=$4} /Pages occupied by compressor/{c=$5}
              END{gsub("\\\\.","",a); gsub("\\\\.","",w); gsub("\\\\.","",c); print (a+w+c)*p}')
            MEM=$(awk -v u="$USEDP" -v t="$TOTAL" 'BEGIN{ if(t>0) printf "%.0f", u/t*100; else print 0 }')
            USEDG=$(awk -v u="$USEDP" 'BEGIN{printf "%.1f", u/1073741824}')
            TOTG=$(awk -v t="$TOTAL" 'BEGIN{printf "%.0f", t/1073741824}')

            # Feed the sparklines (0..1) and update the chip.
            # The graphs follow their own toggle, read at runtime like the
            # other widgets, so flipping them never rebuilds the bar.
            if grep -qx "system-graphs" "$HOME/.config/panewright/.widgets-enabled" 2>/dev/null; then
              GRAPHS=(--set sys.cpu.graph drawing=on --set sys.mem.graph drawing=on)
            else
              GRAPHS=(--set sys.cpu.graph drawing=off --set sys.mem.graph drawing=off)
            fi
            "$BAR" --push sys.cpu.graph "$(awk -v c="$CPU" 'BEGIN{print c/100}')" \\
                   --push sys.mem.graph "$(awk -v m="$MEM" 'BEGIN{print m/100}')" \\
                   "${GRAPHS[@]}" \\
                   --set sys label="CPU ${CPU}%  MEM ${MEM}%"

            # Only compute the panel body when it's actually open.
            OPEN=$("$BAR" --query sys 2>/dev/null | /usr/bin/python3 -c \\
              'import sys,json; print(json.load(sys.stdin).get("popup",{}).get("drawing",""))' 2>/dev/null)
            [ "$OPEN" != "on" ] && exit 0

            LOAD=$(sysctl -n vm.loadavg 2>/dev/null | tr -d '{}' | awk '{printf "%s %s %s", $1,$2,$3}')
            UP=$(uptime | sed -E 's/.*up ([^,]*),.*/\\1/' | xargs)
            ARGS=(--set sys.pop.load label="load $LOAD   ·   up $UP")
            ARGS+=(--set sys.pop.mem label="mem ${USEDG}G / ${TOTG}G used")
            # Top 5 by CPU, then by memory.
            i=1
            while read -r pid pct comm; do
              [ -z "$pid" ] && continue
              ARGS+=(--set sys.pop.cpu.$i label="$(printf '%-16.16s %5s%%' "$comm" "$pct")")
              i=$((i+1)); [ "$i" -gt 5 ] && break
            done < <(ps -Aro pid=,pcpu=,comm= 2>/dev/null | awk '{c=$3; for(j=4;j<=NF;j++) c=c" "$j; sub(".*/","",c); print $1, $2, c}' | head -5)
            i=1
            while read -r pid pct comm; do
              [ -z "$pid" ] && continue
              ARGS+=(--set sys.pop.mem.$i label="$(printf '%-16.16s %5s%%' "$comm" "$pct")")
              i=$((i+1)); [ "$i" -gt 5 ] && break
            done < <(ps -Amo pid=,pmem=,comm= 2>/dev/null | awk '{c=$3; for(j=4;j<=NF;j++) c=c" "$j; sub(".*/","",c); print $1, $2, c}' | head -5)
            "$BAR" "${ARGS[@]}"
            """

        let tooltipPlugin = """
            #!/bin/bash
            export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
            # Generated by Panewright. Hover a widget for HOLD seconds and its
            # popup (the widget's name, or its detail panel) appears; leaving
            # hides it again. A token file makes the delayed reveal cancelable,
            # so passing the cursor over a chip never flashes a tooltip.
            BAR="$(command -v sketchybar)"
            STATE="$HOME/.config/panewright/.tooltip"
            HOLD=3
            case "$SENDER" in
              mouse.entered)
                TOKEN="$NAME.$RANDOM$RANDOM"
                printf '%s' "$TOKEN" > "$STATE"
                (
                  sleep "$HOLD"
                  # Only reveal if this hover is still the current one.
                  [ "$(cat "$STATE" 2>/dev/null)" = "$TOKEN" ] &&
                    "$BAR" --set "$NAME" popup.drawing=on
                ) >/dev/null 2>&1 &
                ;;
              mouse.exited)
                : > "$STATE"
                "$BAR" --set "$NAME" popup.drawing=off
                ;;
            esac
            exit 0
            """

        let m = config.modules
        let widgetsPlugin = """
            #!/bin/bash
            export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
            # Generated by Panewright. Refreshes every enabled widget in ONE
            # batched sketchybar call — one process per cycle, not one per
            # widget. All data is no-sudo, no-SIP.
            BAR="$(command -v sketchybar)"
            A=/opt/homebrew/bin/aerospace
            STATE="$HOME/.config/panewright/.widget-state"
            # Which widgets are on is read at RUNTIME from this file, not baked
            # into the script — so toggling one is a config write plus a
            # trigger, never a bar reload (which visibly tore the bar down).
            ENABLED="$HOME/.config/panewright/.widgets-enabled"
            on() { grep -qx "$1" "$ENABLED" 2>/dev/null; }
            ARGS=()

            if on network; then
            # Throughput from interface byte counters vs. the last cycle.
            IFACE=$(route -n get default 2>/dev/null | awk '/interface:/{print $2}')
            read -r RX TX <<<"$(netstat -ib 2>/dev/null | awk -v i="$IFACE" '$1==i && $7 ~ /^[0-9]+$/ {print $7, $10; exit}')"
            NOW=$(date +%s)
            if [ -f "$STATE" ]; then read -r PRX PTX PT < "$STATE"; else PRX=$RX; PTX=$TX; PT=$((NOW-1)); fi
            printf '%s %s %s\\n' "${RX:-0}" "${TX:-0}" "$NOW" > "$STATE"
            DT=$((NOW - PT)); [ "$DT" -lt 1 ] && DT=1
            human() { awk -v b="$1" 'BEGIN{ if(b>1048576) printf "%.1fM", b/1048576; else if(b>1024) printf "%.0fK", b/1024; else printf "%dB", b }'; }
            DOWN=$(human $(( (${RX:-0} - ${PRX:-0}) / DT )))
            UP=$(human $(( (${TX:-0} - ${PTX:-0}) / DT )))
            ARGS+=(--set w.net drawing=on label="↓$DOWN ↑$UP")
            else
              ARGS+=(--set w.net drawing=off)
            fi

            if on ports; then
            PORTS=$(lsof -iTCP -sTCP:LISTEN -P -n 2>/dev/null | awk 'NR>1{split($9,a,":"); print a[length(a)], $1}' | sort -un | head -8)
            COUNT=$(printf '%s\\n' "$PORTS" | grep -c . )
            ARGS+=(--set w.ports drawing=on label="⇄ $COUNT")
            i=1
            while read -r p proc; do
              [ -z "$p" ] && continue
              ARGS+=(--set w.ports.$i drawing=on label="$(printf ':%-6s %s' "$p" "$proc")")
              i=$((i+1)); [ "$i" -gt 8 ] && break
            done <<< "$PORTS"
            while [ "$i" -le 8 ]; do ARGS+=(--set w.ports.$i drawing=off); i=$((i+1)); done
            else
              ARGS+=(--set w.ports drawing=off)
              for i in $(seq 1 8); do ARGS+=(--set w.ports.$i drawing=off); done
            fi

            if on disk; then
            read -r DPCT DFREE <<<"$(df -k / | awk 'NR==2{printf "%d %.0f", $5, $4/1048576}')"
            ARGS+=(--set w.disk drawing=on label="SSD ${DPCT}% · ${DFREE}G free")
            else
              ARGS+=(--set w.disk drawing=off)
            fi

            if on battery; then
            BINFO=$(pmset -g batt 2>/dev/null | tail -1)
            BPCT=$(printf '%s' "$BINFO" | grep -oE '[0-9]+%' | head -1)
            BREM=$(printf '%s' "$BINFO" | grep -oE '[0-9]+:[0-9]+' | head -1)
            case "$BINFO" in *charging*) BSYM="⚡";; *) BSYM="";; esac
            ARGS+=(--set w.batt drawing=on label="${BSYM}${BPCT:-?}${BREM:+ · $BREM}")
            else
              ARGS+=(--set w.batt drawing=off)
            fi

            if on docker; then
            if command -v docker >/dev/null 2>&1; then
              DC=$(docker ps -q 2>/dev/null | grep -c .)
              ARGS+=(--set w.docker drawing=on label="⬢ $DC")
            else
              ARGS+=(--set w.docker drawing=off)
            fi
            else
              ARGS+=(--set w.docker drawing=off)
            fi

            if on cloud-context; then
            # Highlight anything that looks like production — this widget's
            # whole point is catching "wait, which cluster am I on?".
            CTX=""
            command -v kubectl >/dev/null 2>&1 && CTX=$(kubectl config current-context 2>/dev/null)
            [ -n "$AWS_PROFILE" ] && CTX="${CTX:+$CTX · }aws:$AWS_PROFILE"
            if [ -n "$CTX" ]; then
              case "$CTX" in *prod*|*production*) CCOL=\(accent);; *) CCOL=\(palette.dim);; esac
              ARGS+=(--set w.cloud drawing=on label="$CTX" label.color=$CCOL)
            else
              ARGS+=(--set w.cloud drawing=off)
            fi
            else
              ARGS+=(--set w.cloud drawing=off)
            fi



            if on scratchpad; then
            SC=$("$A" list-windows --workspace S --format '%{window-id}' 2>/dev/null | grep -c .)
            if [ "${SC:-0}" -gt 0 ]; then
              ARGS+=(--set w.scratch drawing=on label="⇩ $SC")
            else
              ARGS+=(--set w.scratch drawing=off)
            fi
            else
              ARGS+=(--set w.scratch drawing=off)
            fi

            if on mic-mute; then
            MIC=$(osascript -e 'input volume of (get volume settings)' 2>/dev/null)
            if [ "${MIC:-0}" -eq 0 ] 2>/dev/null; then
              ARGS+=(--set w.mic drawing=on label="🎤⃠" label.color=\(accent))
            else
              ARGS+=(--set w.mic drawing=on label="🎤" label.color=\(palette.dim))
            fi
            else
              ARGS+=(--set w.mic drawing=off)
            fi

            if on volume; then
            VOL=$(osascript -e 'output volume of (get volume settings)' 2>/dev/null)
            MUTED=$(osascript -e 'output muted of (get volume settings)' 2>/dev/null)
            if [ "$MUTED" = "true" ]; then VSYM="🔇"; else VSYM="🔊"; fi
            ARGS+=(--set w.vol drawing=on label="$VSYM ${VOL:-0}%")
            else
              ARGS+=(--set w.vol drawing=off)
            fi

            if on brew-updates; then
            # brew outdated is slow, so cache it and refresh at most hourly.
            BREWC="$HOME/.config/panewright/.brew-outdated"
            # The app refreshes this cache hourly. Running `brew` here instead
            # returned 0: SketchyBar's spawn environment makes brew produce
            # nothing, though the identical command works in a normal shell.
            BREWN=$(cat "$BREWC" 2>/dev/null | tr -dc '0-9')
            if [ "${BREWN:-0}" -gt 0 ] 2>/dev/null; then
              ARGS+=(--set w.brew drawing=on label="⬆ ${BREWN}" label.color=\(accent))
            else
              ARGS+=(--set w.brew drawing=off)
            fi
            else
              ARGS+=(--set w.brew drawing=off)
            fi

            if on vpn; then
            # A utun with a peer address means a tunnel is actually carrying
            # traffic; macOS keeps empty utun interfaces around regardless.
            if ifconfig 2>/dev/null | awk '/^utun/{i=$1} /inet .*-->/{if(i)print i}' | grep -q .; then
              ARGS+=(--set w.vpn drawing=on label="VPN" label.color=\(accent))
            else
              ARGS+=(--set w.vpn drawing=off)
            fi
            else
              ARGS+=(--set w.vpn drawing=off)
            fi

            if on keyboard-layout; then
            KBD=$(defaults read ~/Library/Preferences/com.apple.HIToolbox.plist AppleSelectedInputSources 2>/dev/null \\
              | awk -F'"' '/KeyboardLayout Name/{print $4; exit}')
            [ -n "$KBD" ] && ARGS+=(--set w.kbd drawing=on label="$KBD") \\
                          || ARGS+=(--set w.kbd drawing=off)
            else
              ARGS+=(--set w.kbd drawing=off)
            fi

            if on focus-mode; then
            FOCUS="$HOME/Library/DoNotDisturb/DB/Assertions.json"
            if [ -s "$FOCUS" ] && /usr/bin/python3 -c \\
              'import json,sys; d=json.load(open(sys.argv[1])); sys.exit(0 if d.get("data",[{}])[0].get("storeAssertionRecords") else 1)' \\
              "$FOCUS" 2>/dev/null; then
              ARGS+=(--set w.focus drawing=on label="🌙" label.color=\(accent))
            else
              ARGS+=(--set w.focus drawing=off)
            fi
            else
              ARGS+=(--set w.focus drawing=off)
            fi

            if on now-playing; then
            NP=""
            for APP in Spotify Music; do
              if pgrep -x "$APP" >/dev/null 2>&1; then
                STATE=$(osascript -e "tell application \\"$APP\\" to player state as string" 2>/dev/null)
                if [ "$STATE" = "playing" ]; then
                  NP=$(osascript -e "tell application \\"$APP\\" to (name of current track) & \\" — \\" & (artist of current track)" 2>/dev/null)
                  break
                fi
              fi
            done
            if [ -n "$NP" ]; then
              ARGS+=(--set w.play drawing=on label="♪ $(printf '%.28s' "$NP")")
            else
              ARGS+=(--set w.play drawing=off)
            fi
            else
              ARGS+=(--set w.play drawing=off)
            fi

            if on weather; then
            # One network call an hour, cached; the bar never blocks on it.
            WC="$HOME/.config/panewright/.weather"
            if [ ! -f "$WC" ] || [ $(( $(date +%s) - $(stat -f %m "$WC" 2>/dev/null || echo 0) )) -gt 3600 ]; then
              curl -sf --max-time 5 'https://wttr.in/?format=%c%t' -o "$WC.tmp" 2>/dev/null &&
                [ -s "$WC.tmp" ] && mv "$WC.tmp" "$WC"
            fi
            WX=$(cat "$WC" 2>/dev/null | tr -d '+' | head -c 20)
            [ -n "$WX" ] && ARGS+=(--set w.weather drawing=on label="$WX") \\
                         || ARGS+=(--set w.weather drawing=off)
            else
              ARGS+=(--set w.weather drawing=off)
            fi

            [ ${#ARGS[@]} -gt 0 ] && "$BAR" "${ARGS[@]}"
            exit 0
            """

        let reorderPlugin = """
            #!/bin/bash
            export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
            # Generated by Panewright. Several plugins add right-side items
            # independently, and each reordering only its own items left the
            # groups interleaved — to-do pills drifting away from their "+"
            # button, widgets landing between them. This is the SINGLE ordering
            # authority for the whole right side: widgets (in the user's order,
            # graphs kept beside their chip), then to-dos with their + button,
            # then integrations.
            BAR="$(command -v sketchybar)"
            ORDERFILE="$HOME/.config/panewright/.widgets-order"
            LEFT=""
            for i in $(seq 0 9); do
              "$BAR" --query pill.$i >/dev/null 2>&1 && LEFT="$LEFT pill.$i"
            done
            if [ -n "$LEFT" ]; then
              "$BAR" --reorder \(spaceOrder) \\
                mode front_app $LEFT
            fi
            ORDER=""
            while read -r item; do
              [ -z "$item" ] && continue
              "$BAR" --query "$item" >/dev/null 2>&1 && ORDER="$ORDER $item"
            done < "$ORDERFILE" 2>/dev/null
            for i in $(seq 0 19); do
              "$BAR" --query todo.item.$i >/dev/null 2>&1 && ORDER="$ORDER todo.item.$i"
            done
            "$BAR" --query todo >/dev/null 2>&1 && ORDER="$ORDER todo"
            for i in $(seq 0 5); do
              "$BAR" --query integration.$i >/dev/null 2>&1 && ORDER="$ORDER integration.$i"
            done
            [ -n "$ORDER" ] && "$BAR" --reorder $ORDER
            """

        return Files(
            sketchybarrc: rc + "\n",
            workspacesPlugin: workspacesPlugin + "\n",
            modePlugin: modePlugin + "\n",
            frontAppPlugin: frontAppPlugin + "\n",
            todoPlugin: todoPlugin + "\n",
            integrationsPlugin: integrationsPlugin + "\n",
            reorderPlugin: reorderPlugin + "\n",
            pillsPlugin: pillsPlugin + "\n",
            systemPlugin: systemPlugin + "\n",
            widgetsPlugin: widgetsPlugin + "\n",
            tooltipPlugin: tooltipPlugin + "\n")
    }

    /// Anchor that drives the integrations plugin; the pills it creates sit
    /// to its left.
    private static func integrationsItem(accent: String) -> String {
        """
        $BAR --add item integrations right \\
          --set integrations update_freq=120 drawing=off \\
            script="$PLUGINS/panewright_integrations.sh" \\
          --subscribe integrations panewright_integrations
        """
    }

    /// Every opt-in widget's bar item, plus the single hidden driver that
    /// refreshes them all. One driver — not one poller per widget — keeps this
    /// to a single process per cycle and one batched `--set`.
    private static func widgetItems(
        _ modules: PanewrightConfig.Modules, accent: String, palette: Palette
    ) -> String {
        var lines: [String] = []
        // Hovering a widget for a beat names it — these chips are terse by
        // design, so the tooltip is how you learn what "⇄ 8" means.
        func tooltip(_ name: String, _ text: String) -> String {
            """
            $BAR --set \(name) popup.background.corner_radius=8 \
            popup.background.border_width=1 popup.background.color=0xf01a1a22 \
            popup.background.border_color=0x44ffffff popup.horizontal=off \
            popup.align=right popup.y_offset=-6 script="$PLUGINS/panewright_tooltip.sh" \
            --add item \(name).tip popup.\(name) \
            --set \(name).tip label="\(text)" label.font="\(palette.font)" \
            label.color=\(palette.dim) label.padding_left=10 label.padding_right=10 \
            --subscribe \(name) mouse.entered mouse.exited
            """
        }
        /// `key` is the config key, so right-click can turn the widget off.
        func chip(_ name: String, _ key: String, _ tip: String, click: String? = nil) {
            // Right-click always disables; left-click runs the widget's own
            // action when it has one.
            let disable = "open 'panewright://widgets/disable/\(key)'"
            let action =
                click.map { "if [ \\\"$BUTTON\\\" = \\\"right\\\" ]; then \(disable); else \($0); fi" }
                ?? "if [ \\\"$BUTTON\\\" = \\\"right\\\" ]; then \(disable); fi"
            lines.append(
                "$BAR --add item \(name) right --set \(name) label=\"…\" drawing=off"
                    + " label.font=\"\(palette.font)\" label.padding_left=8 label.padding_right=8"
                    + " background.corner_radius=6 background.height=20"
                    + " click_script=\"\(action)\"")
            lines.append(tooltip(name, tip))
        }
        /// Ports already unfurls a list on click, so its popup leads with a
        /// title row that doubles as the hover tooltip.
        func portsChip() {
            let disable = "open 'panewright://widgets/disable/ports'"
            lines.append(
                "$BAR --add item w.ports right --set w.ports label=\"…\" drawing=off"
                    + " label.font=\"\(palette.font)\" label.padding_left=8 label.padding_right=8"
                    + " background.corner_radius=6 background.height=20"
                    + " popup.background.corner_radius=8 popup.background.border_width=1"
                    + " popup.background.color=0xf01a1a22 popup.background.border_color=0x44ffffff"
                    + " popup.horizontal=off popup.align=right popup.y_offset=-6"
                    + " script=\"$PLUGINS/panewright_tooltip.sh\""
                    + " click_script=\"if [ \\\\\\\"$BUTTON\\\\\\\" = \\\\\\\"right\\\\\\\" ]; then \(disable);"
                    + " else $BAR --set w.ports popup.drawing=toggle; fi\"")
            lines.append(
                "$BAR --add item w.ports.tip popup.w.ports --set w.ports.tip"
                    + " label=\"Listening ports\" label.font=\"\(palette.font)\""
                    + " label.color=\(accent) label.padding_left=10 label.padding_right=10")
            for i in 1...8 {
                lines.append(
                    "$BAR --add item w.ports.\(i) popup.w.ports --set w.ports.\(i) label=\"…\""
                        + " label.font=\"\(palette.font)\" label.padding_left=10"
                        + " label.padding_right=10 label.color=\(palette.dim)")
            }
            lines.append("$BAR --subscribe w.ports mouse.entered mouse.exited")
        }
        // Emitted in the user's configured order. SketchyBar stacks `right`
        // items leftward, so the list is reversed: the first configured widget
        // ends up leftmost, matching what the picker shows top to bottom.
        let specs: [String: (item: String, tip: String, click: String?)] = [
            "weather": ("w.weather", "Weather · current conditions", nil),
            "now-playing": (
                "w.play", "Now playing · click to play/pause",
                "osascript -e 'tell application \\\"Spotify\\\" to playpause' 2>/dev/null || osascript -e 'tell application \\\"Music\\\" to playpause'"),
            "focus-mode": ("w.focus", "Focus · Do Not Disturb state", nil),
            "keyboard-layout": ("w.kbd", "Keyboard · input source", nil),
            "vpn": ("w.vpn", "VPN · tunnel status", nil),
            "brew-updates": ("w.brew", "Homebrew · outdated packages", "open -a Terminal"),
            "volume": (
                "w.vol", "Volume · click to mute",
                "osascript -e 'set volume output muted (not (output muted of (get volume settings)))'"),
            "mic-mute": ("w.mic", "Microphone · click to toggle mute", "$SCRIPTS_DIR/mic-toggle.sh"),
            "scratchpad": ("w.scratch", "Scratchpad · stashed windows", nil),
            "cloud-context": ("w.cloud", "kubectl context / AWS profile", nil),
            "docker": ("w.docker", "Docker · running containers", nil),
            "battery": ("w.batt", "Battery · charge and time left", nil),
            "disk": ("w.disk", "Disk · boot volume", nil),
            "network": ("w.net", "Network · down / up per second", nil),
        ]
        for key in modules.resolvedOrder.reversed() {
            if key == "ports" {
                portsChip()
            } else if let spec = specs[key] {
                chip(spec.item, key, spec.tip, click: spec.click)
            }
        }
        lines.append(
            "$BAR --add item widgets_driver right --set widgets_driver drawing=off"
                + " update_freq=5 script=\"$PLUGINS/panewright_widgets.sh\""
                + " --subscribe widgets_driver panewright_widgets")
        return lines.joined(separator: "\n")
    }

    /// The system-monitor module: two live sparkline graphs (CPU, memory) and
    /// a chip that unfurls a mini-htop perf panel on click. All items are
    /// created once here; the plugin only `--set`s labels and `--push`es graph
    /// values, so nothing is added/removed at runtime (no flicker, no churn).
    private static func systemItem(accent: String, palette: Palette) -> String {
        // Popup rows are created once, relabeled every cycle by the plugin.
        func rows(_ kind: String) -> String {
            (1...5).map {
                "$BAR --add item sys.pop.\(kind).\($0) popup.sys --set sys.pop.\(kind).\($0)"
                    + " label=\"…\" label.font=\"\(palette.font)\""
                    + " label.padding_left=10 label.padding_right=10 label.color=\(palette.dim)"
            }.joined(separator: "\n")
        }
        let cpuRows = rows("cpu")
        let memRows = rows("mem")
        return """
            # Two sparkline graphs + a chip, right side. The chip's popup holds
            # the perf panel; a click toggles it.
            # Graphs are their own toggle — the readout can stand alone.
            $BAR --add graph sys.cpu.graph right 32 \\
              --set sys.cpu.graph graph.color=\(accent) graph.fill_color=\(accent)44 \\
                background.height=20 label.drawing=off icon.drawing=off \\
                width=32 update_freq=3 script="$PLUGINS/panewright_system.sh"
            $BAR --add graph sys.mem.graph right 32 \\
              --set sys.mem.graph graph.color=\(palette.dim) graph.fill_color=\(palette.dim)33 \\
                background.height=20 label.drawing=off icon.drawing=off width=32
            $BAR --add item sys right \\
              --set sys label="…" label.font="\(palette.font)" \\
                label.padding_left=8 label.padding_right=8 \\
                background.corner_radius=6 background.height=20 \\
                popup.background.corner_radius=8 popup.background.border_width=1 \\
                popup.background.color=0xf01a1a22 popup.background.border_color=0x44ffffff \\
                popup.horizontal=off popup.align=right popup.y_offset=-6 \\
                script="$PLUGINS/panewright_tooltip.sh" \\
                click_script="$BAR --set sys popup.drawing=toggle" \\
              --subscribe sys mouse.entered mouse.exited
            # Perf-panel rows (updated by the plugin each cycle).
            $BAR --add item sys.pop.load popup.sys \\
              --set sys.pop.load label="…" label.font="\(palette.font)" \\
                label.padding_left=10 label.padding_right=10
            $BAR --add item sys.pop.mem popup.sys \\
              --set sys.pop.mem label="…" label.font="\(palette.font)" \\
                label.padding_left=10 label.padding_right=10
            $BAR --add item sys.pop.hcpu popup.sys \\
              --set sys.pop.hcpu label="TOP · CPU" label.font="\(palette.font)" \\
                label.color=\(accent) label.padding_left=10 label.padding_right=10
            \(cpuRows)
            $BAR --add item sys.pop.hmem popup.sys \\
              --set sys.pop.hmem label="TOP · MEMORY" label.font="\(palette.font)" \\
                label.color=\(accent) label.padding_left=10 label.padding_right=10
            \(memRows)
            $BAR --add item sys.pop.act popup.sys \\
              --set sys.pop.act label="Open Activity Monitor" label.font="\(palette.font)" \\
                label.color=\(palette.dim) label.padding_left=10 label.padding_right=10 \\
                click_script="open -a 'Activity Monitor'; $BAR --set sys popup.drawing=off"
            """
    }

    /// The anchor item: a "+" button on the right that also drives the
    /// plugin, which grows one pill per task leftward from it.
    private static func todoItem(accent: String) -> String {
        """
        $BAR --add item todo right \\
          --set todo update_freq=60 script="$PLUGINS/panewright_todo.sh" \\
            label="+" label.color=\(accent) \\
            label.padding_left=8 label.padding_right=8 \\
            background.corner_radius=6 background.height=20 \\
            background.color=0x22ffffff background.drawing=on \\
            click_script="$SCRIPTS_DIR/todo-add.sh" \\
          --subscribe todo panewright_todo
        """
    }

    /// The keybinding-conflict chip: amber, right-aligned, and absent entirely
    /// when the keymap is clean — a warning that's always there is wallpaper.
    /// Conflicts are known at emit time (they're a property of the config), so
    /// this needs no plugin or polling; regenerating the bar is what refreshes it.
    ///
    /// The count is *rows*, not findings — it has to match what clicking
    /// through actually shows, and it's a count of decisions to make, not of
    /// sentences to read.
    static func conflictsItem(count: Int) -> String {
        guard count > 0 else { return "" }
        return """
            $BAR --add item conflicts right \\
              --set conflicts label="⚠ \(count)" label.color=\(warningColor) \\
                label.padding_left=8 label.padding_right=8 \\
                background.corner_radius=6 background.height=20 \\
                background.color=0x22e0af68 background.drawing=on \\
                click_script="open 'panewright://conflicts'"
            """
    }

    /// Emitted before every other right-side item on purpose. SketchyBar
    /// orders a side by insertion, and the to-do plugin grows its pills
    /// leftward from its anchor — so a chip added after the anchor lands
    /// *between* the "+" and the first task, splitting that group in half.
    /// First means the far right edge: outside every cluster, and the most
    /// visible place for a warning.
    ///
    /// Amber in both themes — it has to read as "look at this" against the
    /// native bar's vibrancy and the technical theme's slate alike.
    static let warningColor = "0xffe0af68"
}
