/// Generates SketchyBar's config script and plugins from a PanewrightConfig.
/// Two aesthetics, one toggle: native (SF Pro, vibrancy, floating pill) and
/// technical (monospace, square, solid). The accent color follows the focus
/// border so the whole system reads as one theme.
public enum SketchyBarConfigEmitter {
    public struct Files: Equatable, Sendable {
        public var sketchybarrc: String
        public var workspacesPlugin: String
        public var modePlugin: String
        public var frontAppPlugin: String
        public var clockPlugin: String
    }

    private struct Palette {
        let barProps: String
        let font: String
        let text: String
        let dim: String
    }

    private static func palette(for theme: PanewrightConfig.StatusBar.Theme) -> Palette {
        switch theme {
        case .native:
            Palette(
                barProps:
                    "height=30 corner_radius=9 margin=8 y_offset=5 blur_radius=30 color=0x2c000000",
                font: "SF Pro:Semibold:13.0",
                text: "0xffffffff",
                dim: "0x80ffffff")
        case .technical:
            Palette(
                barProps:
                    "height=26 corner_radius=0 margin=0 y_offset=0 blur_radius=0 color=0xf016161e",
                font: "SF Mono:Bold:12.0",
                text: "0xffc0caf5",
                dim: "0x66c0caf5")
        }
    }

    public static func emit(_ config: PanewrightConfig) throws -> Files {
        let accent = String(
            format: "0x%08x", try ColorHex.argb(fromCSSHex: config.focusBorder.activeColor))
        let palette = palette(for: config.statusBar.theme)
        let workspaces = AeroSpaceConfigEmitter.workspaceNumbers(in: config.bindings)
        let workspaceList = workspaces.map(String.init).joined(separator: " ")

        let rc = """
            #!/bin/bash
            # Generated by Panewright — do not edit by hand.
            # Edit panewright.toml (or use the Panewright app) instead.
            PLUGINS="$HOME/.config/sketchybar/plugins"
            BAR=/opt/homebrew/bin/sketchybar

            $BAR --bar position=top sticky=on \(palette.barProps)
            $BAR --default icon.font="\(palette.font)" label.font="\(palette.font)" \\
                icon.color=\(palette.text) label.color=\(palette.text) \\
                padding_left=4 padding_right=4

            $BAR --add event aerospace_workspace_change
            $BAR --add event panewright_mode

            for sid in \(workspaceList); do
              $BAR --add item space.$sid left \\
                --set space.$sid label="$sid" \\
                  label.padding_left=8 label.padding_right=8 \\
                  background.corner_radius=6 background.height=20 background.drawing=off \\
                  click_script="/opt/homebrew/bin/aerospace workspace $sid" \\
                  script="$PLUGINS/panewright_workspaces.sh $sid" \\
                --subscribe space.$sid aerospace_workspace_change
            done

            $BAR --add item mode left \\
              --set mode label="" label.color=\(accent) \\
                script="$PLUGINS/panewright_mode.sh" \\
              --subscribe mode panewright_mode

            $BAR --add item front_app left \\
              --set front_app script="$PLUGINS/panewright_front_app.sh" \\
              --subscribe front_app front_app_switched

            $BAR --add item clock right \\
              --set clock update_freq=30 script="$PLUGINS/panewright_clock.sh"

            $BAR --update
            $BAR --trigger aerospace_workspace_change \\
              FOCUSED_WORKSPACE="$(/opt/homebrew/bin/aerospace list-workspaces --focused)"
            """

        let workspacesPlugin = """
            #!/bin/bash
            # Generated by Panewright. $1 = the workspace this item represents.
            if [ "$1" = "$FOCUSED_WORKSPACE" ]; then
              sketchybar --set "$NAME" background.drawing=on background.color=\(accent) \\
                label.color=0xffffffff
            else
              sketchybar --set "$NAME" background.drawing=off label.color=\(palette.dim)
            fi
            """

        let modePlugin = """
            #!/bin/bash
            # Generated by Panewright. Badge for the active binding mode.
            if [ -z "$MODE" ] || [ "$MODE" = "main" ]; then
              sketchybar --set "$NAME" label=""
            else
              sketchybar --set "$NAME" label="[$(printf '%s' "$MODE" | tr '[:lower:]' '[:upper:]')]"
            fi
            """

        let frontAppPlugin = """
            #!/bin/bash
            # Generated by Panewright.
            sketchybar --set "$NAME" label="$INFO"
            """

        let clockPlugin = """
            #!/bin/bash
            # Generated by Panewright.
            sketchybar --set "$NAME" label="$(date '+%a %b %d  %H:%M')"
            """

        return Files(
            sketchybarrc: rc + "\n",
            workspacesPlugin: workspacesPlugin + "\n",
            modePlugin: modePlugin + "\n",
            frontAppPlugin: frontAppPlugin + "\n",
            clockPlugin: clockPlugin + "\n")
    }
}
