/// Generates SketchyBar's config script and plugins from a PanewrightConfig.
/// Two aesthetics, one toggle: native (SF Pro, vibrancy, floating pill) and
/// technical (monospace, square, solid). The accent color follows the focus
/// border so the whole system reads as one theme.
public enum SketchyBarConfigEmitter {
    public struct Files: Equatable, Sendable {
        public var sketchybarrc: String
        public var workspacesPlugin: String
        public var modePlugin: String
        public var frontAppPlugin: String
        public var todoPlugin: String
        public var integrationsPlugin: String
        public var reorderPlugin: String
        public var pillsPlugin: String
    }

    private struct Palette {
        let barProps: String
        let font: String
        let text: String
        let dim: String
    }

    private static func palette(for theme: PanewrightConfig.StatusBar.Theme) -> Palette {
        switch theme {
        // y_offset carries the bar below the native menu bar on every display
        // (secondary menu bars overlap position=top otherwise). ~24pt menu
        // bar + a little breathing room.
        case .native:
            Palette(
                barProps:
                    "height=30 corner_radius=9 margin=8 y_offset=-28 blur_radius=30 color=0x2c000000",
                font: "SF Pro:Semibold:13.0",
                text: "0xffffffff",
                dim: "0x80ffffff")
        case .technical:
            Palette(
                barProps:
                    "height=26 corner_radius=0 margin=0 y_offset=-24 blur_radius=0 color=0xf016161e",
                font: "SF Mono:Bold:12.0",
                text: "0xffc0caf5",
                dim: "0x66c0caf5")
        }
    }

    /// Vertical space tiles must reserve so the bar isn't covered by windows:
    /// bar height + y-offset + breathing room. The AeroSpace emitter adds
    /// this to outer.top whenever the bar is enabled.
    public static func reservedTopGap(for theme: PanewrightConfig.StatusBar.Theme) -> Int {
        switch theme {
        case .native: 40  // height 30 + y_offset 5 + 5 breathing
        case .technical: 32  // height 26 + 6 breathing
        }
    }

    public static func emit(_ config: PanewrightConfig) throws -> Files {
        let accent = String(
            format: "0x%08x", try ColorHex.argb(fromCSSHex: config.focusBorder.activeColor))
        let palette = palette(for: config.statusBar.theme)
        let workspaces = AeroSpaceConfigEmitter.workspaceNumbers(in: config.bindings)
        let workspaceList = workspaces.map(String.init).joined(separator: " ")
        // Per-display item names, display outer so each monitor's strip
        // stays contiguous left-to-right.
        let spaceOrder = (1...4)
            .flatMap { d in workspaces.map { "space.\(d).\($0)" } }
            .joined(separator: " ")

        let rc = """
            #!/bin/bash
            export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
            # Generated by Panewright — do not edit by hand.
            # Edit panewright.toml (or use the Panewright app) instead.
            PLUGINS="$HOME/.config/sketchybar/plugins"
            SCRIPTS_DIR="$HOME/.config/panewright/scripts"
            BAR=/opt/homebrew/bin/sketchybar

            $BAR --bar position=top sticky=on \(palette.barProps)
            $BAR --default icon.font="\(palette.font)" label.font="\(palette.font)" \\
                icon.color=\(palette.text) label.color=\(palette.text) \\
                padding_left=4 padding_right=4

            $BAR --add event aerospace_workspace_change
            $BAR --add event panewright_mode
            $BAR --add event panewright_todo
            $BAR --add event panewright_integrations
            $BAR --add event panewright_pills

            \(config.pills.enabled ? """
            $BAR --add item pills left \\
              --set pills update_freq=90 drawing=off \\
                script="$PLUGINS/panewright_pills.sh" \\
              --subscribe pills panewright_pills
            """ : "")

            # One workspace strip per display (associated_display), each
            # controlling and reflecting only that monitor. Displays beyond
            # the actual count simply don't render.
            for did in 1 2 3 4; do
              for sid in \(workspaceList); do
                $BAR --add item space.$did.$sid left \\
                  --set space.$did.$sid associated_display=$did label="$sid" \\
                    label.padding_left=8 label.padding_right=8 \\
                    background.corner_radius=6 background.height=20 background.drawing=off \\
                    click_script="$SCRIPTS_DIR/workspace-select.sh $did $sid" \\
                    script="$PLUGINS/panewright_workspaces.sh $did $sid" \\
                  --subscribe space.$did.$sid aerospace_workspace_change
              done
            done

            $BAR --add item mode left \\
              --set mode label="" label.color=\(accent) \\
                script="$PLUGINS/panewright_mode.sh" \\
              --subscribe mode panewright_mode

            $BAR --add item front_app left \\
              --set front_app script="$PLUGINS/panewright_front_app.sh" \\
              --subscribe front_app front_app_switched

            \(config.integrations.anyEnabled ? integrationsItem(accent: accent) : "")
            \(config.todo.enabled ? todoItem(accent: accent) : "")
            # Pin the order explicitly: without this, items can shuffle when
            # the bar re-renders (a screenshot or display change is enough).
            $BAR --reorder \(spaceOrder) mode front_app

            $BAR --update
            # AeroSpace may still be starting (any launch order must work) —
            # retry before painting the initial highlight.
            for attempt in $(seq 1 20); do
              FOCUSED="$(/opt/homebrew/bin/aerospace list-workspaces --focused 2>/dev/null)"
              [ -n "$FOCUSED" ] && break
              sleep 0.5
            done
            $BAR --trigger aerospace_workspace_change FOCUSED_WORKSPACE="$FOCUSED"
            \(config.todo.enabled ? "$BAR --trigger panewright_todo" : "")
            \(config.integrations.anyEnabled ? "$BAR --trigger panewright_integrations" : "")
            """

        let workspacesPlugin = """
            #!/bin/bash
            export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
            # Generated by Panewright. $1 = sketchybar display, $2 = workspace.
            # Highlight when this workspace is the one *this monitor* shows.
            BAR="$(command -v sketchybar)"
            MAP="$HOME/.config/panewright/monitor-map.tsv"
            MON=$(awk -F'\\t' -v d="$1" '$1 == d { print $2 }' "$MAP" 2>/dev/null)
            [ -z "$MON" ] && MON="$1"
            VISIBLE=$(/opt/homebrew/bin/aerospace list-workspaces --monitor "$MON" --visible 2>/dev/null)
            if [ "$2" = "$VISIBLE" ]; then
              "$BAR" --set "$NAME" background.drawing=on background.color=\(accent) \\
                label.color=0xffffffff
            else
              "$BAR" --set "$NAME" background.drawing=off label.color=\(palette.dim)
            fi
            """

        let modePlugin = """
            #!/bin/bash
            export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
            # Generated by Panewright. Badge for the active binding mode.
            if [ -z "$MODE" ] || [ "$MODE" = "main" ]; then
              "$(command -v sketchybar)" --set "$NAME" label=""
            else
              "$(command -v sketchybar)" --set "$NAME" label="[$(printf '%s' "$MODE" | tr '[:lower:]' '[:upper:]')]"
            fi
            """

        let frontAppPlugin = """
            #!/bin/bash
            export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
            # Generated by Panewright.
            "$(command -v sketchybar)" --set "$NAME" label="$INFO"
            """

        let todoPlugin = """
            #!/bin/bash
            export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
            # Generated by Panewright. Renders the to-do item and its popup.
            BAR="$(command -v sketchybar)"
            SCRIPTS="$HOME/.config/panewright/scripts"
            PLUGINS_DIR="$HOME/.config/sketchybar/plugins"
            TODO="$HOME/.config/panewright/todo.txt"
            [ -f "$TODO" ] || touch "$TODO"

            # Storage is TSV: title<TAB>notes. Each task becomes its own pill
            # in the bar, growing leftward from the "+" button; click one to
            # open its editor.
            MAX=6
            for i in $(seq 0 19); do "$BAR" --remove todo.item.$i >/dev/null 2>&1; done

            ORDER=""
            i=0
            while IFS= read -r line; do
              case "$line" in ""|" ") continue ;; esac
              [ "$i" -ge "$MAX" ] && break
              TITLE=$(printf '%s' "$line" | cut -f1)
              NOTES=$(printf '%s' "$line" | cut -f2- -s)
              SHORT=$(printf '%.18s' "$TITLE")
              [ "${#TITLE}" -gt 18 ] && SHORT="$SHORT…"
              [ -n "$NOTES" ] && SHORT="$SHORT ·"
              "$BAR" --add item todo.item.$i right \\
                --set todo.item.$i label="$SHORT" label.color=\(palette.text) \\
                  label.padding_left=8 label.padding_right=8 \\
                  background.corner_radius=6 background.height=20 \\
                  background.color=0x1affffff background.drawing=on \\
                  click_script="$SCRIPTS/todo-edit.sh $((i + 1))"
              ORDER="$ORDER todo.item.$i"
              i=$((i + 1))
            done < "$TODO"

            # awk, not `grep -c || echo 0`: grep prints 0 *and* exits 1 when
            # nothing matches, which yields a two-line "count".
            TOTAL=$(awk 'NF' "$TODO" 2>/dev/null | wc -l | tr -d ' ')
            if [ "$TOTAL" -gt "$MAX" ]; then
              "$BAR" --set todo label="+$((TOTAL - MAX)) more  +"
            else
              "$BAR" --set todo label="+"
            fi
            # One authority for right-side order — see the reorder plugin.
            "$PLUGINS_DIR/panewright_reorder.sh"
            """

        let integrationsPlugin = """
            #!/bin/bash
            export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
            # Generated by Panewright. One pill per enabled service, fed by
            # the status file the app writes: id<TAB>count<TAB>label.
            BAR="$(command -v sketchybar)"
            PLUGINS_DIR="$HOME/.config/sketchybar/plugins"
            STATUS="$HOME/.config/panewright/integrations.status"
            [ -f "$STATUS" ] || exit 0

            for i in $(seq 0 5); do "$BAR" --remove integration.$i >/dev/null 2>&1; done
            i=0
            while IFS=$'\\t' read -r id count label; do
              [ -z "$id" ] && continue
              COLOR=\(palette.dim)
              [ "${count:-0}" -gt 0 ] 2>/dev/null && COLOR=\(accent)
              # Extra left padding on the first pill separates this group
              # from the to-do pills.
              PAD=8
              [ "$i" -eq 0 ] && PAD=20
              "$BAR" --add item integration.$i right \\
                --set integration.$i label="$label ${count:-0}" label.color="$COLOR" \\
                  label.padding_left=$PAD label.padding_right=8 \\
                  background.corner_radius=6 background.height=20 \\
                  background.color=0x1affffff background.drawing=on \\
                  click_script="open 'panewright://integrations/$id'"
              i=$((i + 1))
            done < "$STATUS"
            "$PLUGINS_DIR/panewright_reorder.sh"
            """

        let pillsPlugin = """
            #!/bin/bash
            export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
            # Generated by Panewright. One pill per parked window; click to
            # peek at it, right-click to give it back to the tiling tree.
            BAR="$(command -v sketchybar)"
            A=/opt/homebrew/bin/aerospace
            SCRIPTS="$HOME/.config/panewright/scripts"
            PLUGINS_DIR="$HOME/.config/sketchybar/plugins"
            PILLS="$HOME/.config/panewright/pills.tsv"
            [ -f "$PILLS" ] || touch "$PILLS"

            for i in $(seq 0 9); do "$BAR" --remove pill.$i >/dev/null 2>&1; done
            LIVE=$("$A" list-windows --all --format '%{window-id}' 2>/dev/null | tr -d ' ')
            PARKED=$("$A" list-windows --workspace P --format '%{window-id}' 2>/dev/null | tr -d ' ')

            TMP=$(mktemp)
            i=0
            while IFS=$'\\t' read -r id app title; do
              [ -z "$id" ] && continue
              # Drop pills whose window has closed.
              printf '%s\\n' "$LIVE" | grep -qx "$id" || continue
              printf '%s\\t%s\\t%s\\n' "$id" "$app" "$title" >> "$TMP"
              [ "$i" -ge 10 ] && continue
              LABEL=$(printf '%.14s' "${app:-window}")
              if printf '%s\\n' "$PARKED" | grep -qx "$id"; then
                COLOR=\(palette.dim); MARK="▸"
              else
                COLOR=\(accent); MARK="▾"
              fi
              "$BAR" --add item pill.$i left \\
                --set pill.$i label="$MARK $LABEL" label.color="$COLOR" \\
                  label.padding_left=8 label.padding_right=8 \\
                  background.corner_radius=6 background.height=20 \\
                  background.color=0x1affffff background.drawing=on \\
                  click_script="if [ \\"\\$BUTTON\\" = \\"right\\" ]; then $SCRIPTS/pill-release.sh $id; else $SCRIPTS/pill-toggle.sh $id; fi"
              i=$((i + 1))
            done < "$PILLS"
            mv "$TMP" "$PILLS"
            "$PLUGINS_DIR/panewright_reorder.sh"
            """

        let reorderPlugin = """
            #!/bin/bash
            export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
            # Generated by Panewright. Two plugins add right-side items
            # independently; each reordering only its own items left the
            # groups interleaved. This is the single ordering authority:
            # to-dos, then the add button, then integrations.
            BAR="$(command -v sketchybar)"
            LEFT=""
            for i in $(seq 0 9); do
              "$BAR" --query pill.$i >/dev/null 2>&1 && LEFT="$LEFT pill.$i"
            done
            if [ -n "$LEFT" ]; then
              "$BAR" --reorder \(spaceOrder) mode front_app $LEFT
            fi
            ORDER=""
            for i in $(seq 0 19); do
              "$BAR" --query todo.item.$i >/dev/null 2>&1 && ORDER="$ORDER todo.item.$i"
            done
            "$BAR" --query todo >/dev/null 2>&1 && ORDER="$ORDER todo"
            for i in $(seq 0 5); do
              "$BAR" --query integration.$i >/dev/null 2>&1 && ORDER="$ORDER integration.$i"
            done
            [ -n "$ORDER" ] && "$BAR" --reorder $ORDER
            """

        return Files(
            sketchybarrc: rc + "\n",
            workspacesPlugin: workspacesPlugin + "\n",
            modePlugin: modePlugin + "\n",
            frontAppPlugin: frontAppPlugin + "\n",
            todoPlugin: todoPlugin + "\n",
            integrationsPlugin: integrationsPlugin + "\n",
            reorderPlugin: reorderPlugin + "\n",
            pillsPlugin: pillsPlugin + "\n")
    }

    /// Anchor that drives the integrations plugin; the pills it creates sit
    /// to its left.
    private static func integrationsItem(accent: String) -> String {
        """
        $BAR --add item integrations right \\
          --set integrations update_freq=120 drawing=off \\
            script="$PLUGINS/panewright_integrations.sh" \\
          --subscribe integrations panewright_integrations
        """
    }

    /// The anchor item: a "+" button on the right that also drives the
    /// plugin, which grows one pill per task leftward from it.
    private static func todoItem(accent: String) -> String {
        """
        $BAR --add item todo right \\
          --set todo update_freq=60 script="$PLUGINS/panewright_todo.sh" \\
            label="+" label.color=\(accent) \\
            label.padding_left=8 label.padding_right=8 \\
            background.corner_radius=6 background.height=20 \\
            background.color=0x22ffffff background.drawing=on \\
            click_script="$SCRIPTS_DIR/todo-add.sh" \\
          --subscribe todo panewright_todo
        """
    }
}
