#!/bin/bash
# Set up everything Panewright needs, without destroying anything that's
# already there.
#
#   Scripts/install.sh [--dry-run]
#
# Safe to run repeatedly: every step checks before acting, so a second run on a
# finished machine does nothing and says so.
#
# What it will NOT do: install Homebrew behind your back. That needs an admin
# password and runs a script from the internet, so it's printed for you to run
# yourself rather than piped into a shell on your behalf.
set -uo pipefail

DRY_RUN=false
[ "${1:-}" = "--dry-run" ] && DRY_RUN=true

CONFIG_HOME="$HOME/.config"
BACKUPS="$CONFIG_HOME/panewright/backups/install-$(date +%Y-%m-%d-%H%M%S)"

bold() { printf '\033[1m%s\033[0m\n' "$1"; }
ok()   { printf '  \033[32m✓\033[0m %s\n' "$1"; }
warn() { printf '  \033[33m!\033[0m %s\n' "$1"; }
step() { printf '  \033[36m→\033[0m %s\n' "$1"; }

run() {
    if $DRY_RUN; then
        printf '  \033[90m(dry run) %s\033[0m\n' "$*"
    else
        "$@"
    fi
}

# --- Homebrew ---------------------------------------------------------------

bold "Homebrew"
BREW=""
for candidate in /opt/homebrew/bin/brew /usr/local/bin/brew; do
    [ -x "$candidate" ] && BREW="$candidate" && break
done

if [ -z "$BREW" ]; then
    warn "not installed."
    echo
    echo "  Homebrew's installer needs your admin password, so run it yourself:"
    echo
    echo "    /bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
    echo
    echo "  Then run this script again."
    exit 1
fi
ok "found at $BREW"

# --- Back up anything we're about to replace --------------------------------
#
# Panewright generates ~/.config/aerospace/aerospace.toml and the whole
# ~/.config/sketchybar directory. If you already use those tools, that's your
# work — it gets copied aside first. Files carrying Panewright's own
# "Generated by Panewright" header are skipped, so re-running doesn't pile up
# copies of our own templates.

bold "Existing configuration"
backed_up=0
preserve() {
    local source="$1" relative="$2"
    [ -f "$source" ] || return 0
    grep -q "Generated by Panewright" "$source" 2>/dev/null && return 0
    local target="$BACKUPS/$relative"
    run mkdir -p "$(dirname "$target")"
    run cp "$source" "$target"
    ok "kept $relative"
    backed_up=$((backed_up + 1))
}

preserve "$CONFIG_HOME/aerospace/aerospace.toml" "aerospace/aerospace.toml"
if [ -d "$CONFIG_HOME/sketchybar" ]; then
    while IFS= read -r file; do
        preserve "$file" "sketchybar/${file#"$CONFIG_HOME/sketchybar/"}"
    done < <(find "$CONFIG_HOME/sketchybar" -type f 2>/dev/null)
fi
preserve "$CONFIG_HOME/panewright/panewright.toml" "panewright/panewright.toml"

if [ "$backed_up" -eq 0 ]; then
    ok "nothing of yours to preserve"
else
    ok "$backed_up file(s) copied to $BACKUPS"
fi

# --- Prerequisites ----------------------------------------------------------

bold "Prerequisites"

install_formula() {
    local name="$1" binary="$2"
    shift 2
    if [ -x "$binary" ] || command -v "${binary##*/}" >/dev/null 2>&1; then
        ok "$name already installed"
        return 0
    fi
    step "installing $name…"
    if run "$BREW" install "$@"; then
        ok "$name installed"
    else
        warn "$name failed to install — Panewright will work without it, minus that feature"
    fi
}

# The tiling engine ships inside Panewright.app itself — nothing to install.
# JankyBorders draws the focus ring.
install_formula "JankyBorders" /opt/homebrew/bin/borders \
    FelixKratz/formulae/borders
# SketchyBar is the status bar.
install_formula "SketchyBar" /opt/homebrew/bin/sketchybar \
    FelixKratz/formulae/sketchybar

# --- Fonts ------------------------------------------------------------------
#
# The bar falls back to system fonts without this, so it's a nice-to-have
# rather than a prerequisite.

bold "Fonts"
if [ -f "$HOME/Library/Fonts/SF-Pro.ttf" ] || \
   ls "$HOME/Library/Fonts" 2>/dev/null | grep -qi "sketchybar-app-font"; then
    ok "bar font present"
else
    step "installing sketchybar-app-font…"
    run "$BREW" install --cask font-sketchybar-app-font >/dev/null 2>&1 \
        && ok "font installed" \
        || warn "font not installed — the bar falls back to system fonts"
fi

# --- Summary ----------------------------------------------------------------

echo
bold "Done"
if $DRY_RUN; then
    echo "  Dry run — nothing was changed."
else
    echo "  Launch Panewright. It writes its own configuration on first run,"
    echo "  and grants of Accessibility and Input Monitoring are prompted for"
    echo "  there because they can't be scripted."
    [ "$backed_up" -gt 0 ] && echo "  Your previous configuration is in $BACKUPS"
fi
